stan-dev/stan

- src/stan/prob/distributions/multivariate/continuous/multi_normal.hpp
- src/stan/prob/distributions/multivariate/continuous/multi_normal_cholesky.hpp
- src/stan/prob/distributions/multivariate/continuous/multi_normal_prec.hpp
- src/stan/prob/distributions/multivariate/continuous/multi_student_t.hpp
Simplifies code by changing
boost::math::tools::promote_args<typename scalar_type<T_y>::type, ...>
into
return_type<T_y, ...>
Should have no runtime impact whatsoever.
Compile the corresponding units tests.
None
> Replace promote_args<typename value_type<T>,...> with return_type<T,...>

- src/docs/stan-reference/advanced.tex
"there is" was duplicated within the same sentence
> stan-reference: fix typo in MCMC Sampling (54.2)

- make/cpplint
- makefile
Adds a `cpplint` target in make. Requires cpplint.py to be installed locally.
Runs cpplint with consistent arguments.
Run `make cpplint` from the command line.
None. Doesn't touch code.
None.
Anyone.
> adding cpplint target

- src/stan/services/init/initialize_state.hpp
- src/test/unit/services/init/initialize_state_test.cpp
Print errors in random initialization.
These were accidentally omitted. This should help make debugging models a little easier.
Run the model in #1326. This should now print error messages.
None.
None.
Bob.
> Print error messages in initialization

- CONTRIBUTING.md
Added a `CONTRIBUTING.md` file that:
1. Includes links for each issue tracker with pre-populated templates.
2. Describes what we expect in a bug report and a feature request in Stan.
Makes it easier for users to generate issues that are descriptive.
Click on all the links.
None.
This is all doc. No change to code.
@bob-carpenter. Mind taking a look and updating the file? Or describing what changes you want.
> adding a CONTRIBUTING.md file

- src/docs/stan-reference/programming.tex
The parameters of the categorical distributions were named $\theta$ and $\phi$ everywhere else in the naive bayes section, but here they appear as $\theta$ and $\pi$.
> stan-reference: fix typo in naive bayes

- src/test/prob/wiener/wiener_test.hpp
`# cpplint --output=vs7 --counting=detailed --root=src --exten
sion=hpp,cpp --filter=-runtime/indentation_namespace,-readability/namespace,-legal/copyright,-whitespace/indent,-runtime/reference src/test/prob/wiener/wiener_test.hpp
Done processing src/test/prob/wiener/wiener_test.hpp
Total errors found: 0`
> wiener_test now linter-friendly

- src/docs/stan-reference/programming.tex
> stan-reference: fix typo

- src/docs/stan-reference/programming.tex
Fix typo in stan-reference ("Softmax with K vs. K −1 Parameters" in section 19.1)
This equation came from "\sum_{k=1}^K \theta_k = 1".
> stan-reference: fix typo in "Problematic Posteriors"

- src/docs/stan-reference/programming.tex
Fixes a few small typos in the Programming Techniques chapter.
> Typos in Programming Techniques chapter

- src/docs/stan-reference/algorithms.tex
> stan-reference: fix typo in HMC (56.1)

- src/docs/stan-reference/programming.tex
Fixed some minor typos in the manual - mostly misspellings and redundant words, all in src/docs/stan-reference/programming.tex
Althogh -> Although
accomodate -> accommodate
cumultive -> cumulative
autogression -> autoregressive
throgh -> through
probabilty -> probability
flexiblity -> flexibility
pulation -> population
enusre -> ensure
possibiliites -> possibilities
suriviving -> surviving
intial -> initial
whehter -> whether
presense -> presence
datatabse -> database
swtiching -> switching
exploratora -> exploratory
posteiror -> posterior
subsituting -> substituting
multivarate -> multivariate
correspdonding -> corresponding
correspdong -> corresponding
functionalty -> functionality
maringal -> marginal
statisticaly -> statistically
arounds -> around
probabilty -> probability
therefor -> …
> fixed a few typos

- makefile
Fixes makefile target for updating the math library.
Try something like:
```
> make math-update/develop
```
Under the current branch, it tries to check out a branch `develop.d` (from our dependency makefile magic) and also `develop`. This fixes the problem.
None.
None.
No one.
> updating makefile

- src/stan/variational/families/normal_fullrank.hpp
This fixes the failed unit test that @syclik noted in a [cmdstan pull request](https://github.com/stan-dev/cmdstan/pull/117), caused by dimensions not matching when calculating the gradient of the ELBO.
Unit test passes.
In cmdstan:
```{bash}
make test/interface/services/argument_configuration_test
test/interface/services/argument_configuration_test
```
None
None
@syclik
> Bugfix fix full rank dimension when calculating gradient

- src/docs/stan-reference/advanced.tex
- src/docs/stan-reference/algorithms.tex
- src/docs/stan-reference/introduction.tex
- src/docs/stan-reference/process.tex
- src/docs/stan-reference/programming.tex
Fix a number of typos across a few chapters of the manual.
> stan-reference: fix many typos

- src/stan/io/array_var_context.hpp
- src/stan/lang/grammars/functions_grammar_def.hpp
- src/stan/lang/grammars/statement_grammar_def.hpp
- src/stan/lang/grammars/term_grammar_def.hpp
- src/stan/lang/rethrow_located.hpp
- src/stan/services/init/initialize_state.hpp
- src/stan/variational/advi.hpp
- src/stan/variational/families/normal_fullrank.hpp
- src/stan/variational/families/normal_meanfield.hpp
Removes all doxygen warnings.
Run doxygen.
None. No change to code.
All doc.
No one.
> squashing doxygen warnings

- make/os_win
set BIT variable on windows conditionally on running on a 32bit or 64bit machine; this triggers the -m$BIT variable to be set correctly for g++ based (Rtools) windows builds
fix the makefile on windows for 32bit machines. Currently Stan generates 64bit binaries on 32bit machines. Not good.
Run some test for example on a win 32bit machine and a win 64bit machine.
None for Stan, but this change should be propagated to stan-math & cmdstan.
None.
@syclik
> set BIT variable on windows conditionally depending on 32 or 64 bit

- make/libstan
Fixes #1618. Issues with makefile.
Make the Stan makefile a little better.
Everything should work the same way.
Make should run a little quicker, I hope.
None required.
No one.
> Fixed make/libstan similiarly to make/tests

- src/stan/services/arguments/arg_variational.hpp
- src/stan/services/arguments/arg_variational_eta.hpp
Changes an argument name of variational inference, from `eta_adagrad` to `eta`. This follows the greek argument convention used in MCMC, and abstracts away from ADVI's tie to a particular learning rate. To be reviewed in combination with https://github.com/stan-dev/cmdstan/pull/166.
Part of a round of pull requests, splitting out #1590. See #1590 for the blueprint.
Note: I don't suggest we merge this request now, but the request will serve as discussion on whether 1. we should allow these sorts of changes; 2. implement it with backwards-compatibility; 3. wait until Stan 3.0.
None
Run unit tests as typically.
None
None
> Change argument of eta_adagrad to eta

- src/stan/services/mcmc/sample.hpp
- src/stan/services/mcmc/warmup.hpp
Removes a handful of cpplint warnings by changing whitespace.
Reduces the number of cpplint warnings.
Run cpplint.
None.
None.
None.
> Cpplint for recent changes to services

- make/tests
Clean up make/tests.
- Removed some blank lines
- Reordered things to be in alphabetical order
Just cleaning code.
Look at the file.
None.
N/A
No one.
> Reordered makefile dependencies

- src/stan/optimization/bfgs.hpp
- src/stan/optimization/lbfgs_update.hpp
- src/stan/services/arguments/argument.hpp
- src/stan/services/arguments/argument_parser.hpp
- src/stan/services/arguments/categorical_argument.hpp
- src/stan/services/arguments/list_argument.hpp
- src/stan/services/arguments/singleton_argument.hpp
- src/stan/services/arguments/unvalued_argument.hpp
- src/stan/services/arguments/valued_argument.hpp
- src/test/integration/services/arguments/argument_test.cpp
Adds the `explicit` keyword to constructors with one argument.
Code cleanup. Matches closer to #1361.
Visually inspect the code for correctness.
I don't foresee any problems, but may trickle upstream to CmdStan.
None required.
@betanalpha
> Added explicit keyword to constructors with one argument

- make/os_mac
Squashes warning from updated compiler on Mac.
Silences a new warning due to updated toolchain. To silence the cause is going to be more difficult than I'm willing to undertake now.
Run 
```
> ./runTests.py src/test/unit/lang/reject/reject_func_call_model_test.cpp
```
We'll need to see if this breaks on an older clang++. I'm on it.
None.
None.
> Silencing warning from new clang++

- src/stan/services/init/initialize_state.hpp
- src/stan/services/io/write_error_msg.hpp
- src/test/performance/utility.hpp
- src/test/unit/services/init/initialize_state_test.cpp
- src/test/unit/services/io/write_error_msg_test.cpp
Change initialize_state to use the writer callbacks.
Refactor code.
Run.
CmdStan, RStan, and PyStan will need the writer. Action is on me.
Included in the doc.
@betanalpha
> Updated initialize_state to use the writer

- src/stan/mcmc/hmc/base_hmc.hpp
- src/stan/mcmc/hmc/hamiltonians/dense_e_point.hpp
- src/stan/mcmc/hmc/hamiltonians/diag_e_point.hpp
- src/stan/mcmc/hmc/hamiltonians/ps_point.hpp
- src/test/unit/mcmc/hmc/hamiltonians/ps_point_test.cpp
Use the base_writer in ps_point and *_point classes.
None.
None.
This is @betanalpha's code. I reviewed it and it's ok.
> Updating ps_point and points to use writer callback

- src/stan/services/init/initialize_state.hpp
Visual Studio choked on this. Not sure why the other compilers didn't. 
Looks like @syclik has been working on this most recently.
> Fix typo in initialize_state.hpp

- src/stan/io/json/json_data_handler.hpp
- src/stan/io/json/json_handler.hpp
- src/stan/io/json/json_parser.hpp
- src/stan/optimization/lbfgs_update.hpp
Gets cpplint warnings down to 0.
Removes cpplint warnings by any means necessary. =). I nolinted the remaining issues.
Run cpplint! We should have 0 warnings now.
None.
None.
@bob-carpenter. I was slightly lazy and didn't look too carefully at the json code. I've `NOLINT`ed it for now.
If we need to fix it, I think we could open up a new issue to take care of it.
> Cpplint warnings to 0!

- src/stan/command/stanc_helper.hpp
- src/stan/lang/compiler.hpp
- src/stan/lang/parser.hpp
- src/test/unit/lang/compiler_test.cpp
- src/test/unit/lang/utility.hpp
This pull request removes the unused `filename` parameter for the function `parse` (in stan/lang/parser.hpp) and updates all locations where the function is called.
Unit tests pass. Check (previous versions of) stan/lang/parser.hpp to verify that `filename` was unused.
None. No interface uses the parameter.
NA
Anyone.
> Remove unused 'filename' param in stan::lang::parse

- src/stan/lang/generator.hpp
- src/test/test-models/good/fun_log_forward_decl.stan
Remove duplicate definition of `propto=false` version of `_log` user-defined functions when there is a forward declaration.
Allow recursive density definitions.
There is a new model test that passes now and didn't pass before.
None.
Behavior now matches existing doc.
Anyone.
> remove dup def for _log funs, fixing #1768

- src/docs/stan-reference/programming.tex
>  reparameterize tau in example for  hierarchical regression model

- src/docs/stan-reference/advanced.tex
Replace `abs` by `fabs` in lasso example.
> replace deprecated function abs by fabs

- make/libstan
- make/tests
Fixing the makefile so tests depending on stanc automatically rebuild it when headers change.
Makes testing easier.
First build a test. It should build `test/test-models/stanc`. Then run it again and it won't rebuild.
```
./runTests.py src/test/unit/lang/parser/assignment_test.cpp
./runTests.py src/test/unit/lang/parser/assignment_test.cpp
```
Test case 1:
```
touch src/stan/lang/grammars/bare_type_grammar.hpp
./runTests.py src/test/unit/lang/parser/assignment_test.cpp
```
Test case 2:
```
touch src/stan/lang/grammars/bare_type_grammar_def.hpp
./runTests.py src/test/unit/lang/parser/assignment_test.cpp
```
Test case 3:
```
touch src/stan/lang/grammars/bare_type_grammar_inst.cpp
./runTests.py src/test/unit/lang/parser/assignment_test.cpp
```
Prior to this fix, test case 2 would have not …
> Updating makefile so dependencies work properly for stanc

- src/stan/lang/grammars/semantic_actions_def.cpp
- src/test/test-models/good/abs-deprecate.stan
- src/test/unit/lang/parser/assignment_test.cpp
- src/test/unit/lang/parser/expression_grammar_test.cpp
Uses Ben's wording for new message indicating that deprecation of <- is in Stan only.  Also applied to abs(real), the only other confusible deprecation warning.
Not confuse users.
New unit tests.
No.
Anyone.
> deprecation of <- clarified to indicate Stan, fixing #1819

- src/docs/stan-reference/appendices.tex
- src/docs/stan-reference/functions.tex
- src/stan/lang/function_signatures.h
- src/test/test-models/good/function-signatures/math/functions/inc_beta.stan
- src/test/unit/lang/parser/math_functions_test.cpp
Expose the incomplete beta function `B(x; a, b)` as `inc_beta(a, b, x)`.  
I copied the argument order from the math library. Mathematical notation is `B(x; a, b)`, Boost uses `ibeta(a, b, x)`, and and Matlab uses `beta_inc(x, a, b)`.
Allow users to call incomplete beta in Stan progams.
Unit tests for language.  Build and view doc.
No.
Yes, in function list and in appendix for mathematical definition.
Anyone. …
> add incomplete beta as inc_beta

- src/stan/lang/generator.hpp
- src/test/test-models/good/truncation-user-defined.stan
Add `pstream__` argument to user-defined CDFs and CCDFs.
Allow truncation to be used for user-defined densities.
New good model test that'll get picked up on integration tests; wouldn't compile before, compiles now.
None.
Code was fixed to match doc.
Anyone.
> add pstream to cdfs for truncation, fixing #1628

- make/tests
- src/stan/mcmc/hmc/base_hmc.hpp
- src/stan/mcmc/hmc/static_uniform/adapt_dense_e_static_uniform.hpp
- src/stan/mcmc/hmc/static_uniform/adapt_diag_e_static_uniform.hpp
- src/stan/mcmc/hmc/static_uniform/adapt_unit_e_static_uniform.hpp
- src/stan/mcmc/hmc/static_uniform/base_static_uniform.hpp
- src/stan/mcmc/hmc/static_uniform/dense_e_static_uniform.hpp
- src/stan/mcmc/hmc/static_uniform/diag_e_static_uniform.hpp
- src/stan/mcmc/hmc/static_uniform/unit_e_static_uniform.hpp
- src/test/test-models/good/mcmc/hmc/static_uniform/gauss.stan
- src/test/unit/mcmc/hmc/base_static_uniform_test.cpp
- src/test/unit/mcmc/hmc/derived_static_uniform_test.cpp
Adds a static HMC sampler that samples trajectories of fixed sized uniformly around the initial point instead of deterministically forward in time.  Addresses #1849.
Adds a new HMC sampler.
Run tests.
None.
None.
Anyone.
Copyright: Michael Betancourt
> Add uniform static HMC sampler

- src/docs/stan-reference/language.tex
This corrects a minor typo in the introduction to chapter 27.
> Fix minor typo in reference manual.

- make/os_win
- make/tests
- makefile
Updates the Math submodule to the current develop version, ce71d1d.
The Stan Math Library `develop` branch has been updated.
This pull request updates the submodule for the Stan Math Library submodule to ce71d1d.
None.
None.
None.
> Update submodule for the Stan Math Library

- src/stan/services/sample/init_windowed_adapt.hpp
Finishes up #1836. Missed one use.
Needs updates to CmdStan and RStan.
None.
Ben reviewed the last one... this is just an extension of it.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University.
> Adding one more use of error_writer to #1836

- src/stan/mcmc/hmc/nuts/adapt_dense_e_nuts.hpp
- src/stan/mcmc/hmc/static/adapt_dense_e_static_hmc.hpp
- src/stan/mcmc/hmc/static/adapt_diag_e_static_hmc.hpp
Fixes the info vs error stream issue. This is necessary for downstream interfaces being able to separate apart the info from the errors.
> More fixes for streams. This should really fix #1836.

- makefile
added -DNO_FPRINTF_OUTPUT to CFLAGS
align CFLAGS with math
build something
None.
None.
Anyone.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Sebastian Weber
> aligned makefile, fixed #1870

- src/stan/mcmc/hmc/nuts/base_nuts.hpp
- src/stan/mcmc/hmc/xhmc/base_xhmc.hpp
- src/test/unit/mcmc/hmc/nuts/base_nuts_test.cpp
- src/test/unit/mcmc/hmc/nuts/softabs_nuts_test.cpp
- src/test/unit/mcmc/hmc/nuts/unit_e_nuts_test.cpp
- src/test/unit/mcmc/hmc/xhmc/base_xhmc_test.cpp
- src/test/unit/mcmc/hmc/xhmc/softabs_xhmc_test.cpp
- src/test/unit/mcmc/hmc/xhmc/unit_e_xhmc_test.cpp
Fixes the numerical instability of NUTS (and XHMC) that could occur out in the tails of a target distribution.
Avoids the transient warmup issues seen in various models.
Run on any of the models that were proving problematic.  Make sure to use the same seed.
Very small increase in cost due to the extra exps and logs needed for the logarithmic summations, should be negligible.
Not user facing.
@bob-carpenter, @syclik, @wds15 
Copyright: University of Warwick.
> Fixed numerial instability of transition probabilities

- src/stan/mcmc/hmc/nuts/base_nuts.hpp
- src/test/performance/logistic_test.cpp
- src/test/unit/mcmc/hmc/nuts/base_nuts_test.cpp
- src/test/unit/mcmc/hmc/nuts/softabs_nuts_test.cpp
- src/test/unit/mcmc/hmc/nuts/unit_e_nuts_test.cpp
Changes the trajectory -> state transition in NUTS from the naive uniform transition to the "delayed rejection" transition used in the original NUTS implementation.  Addresses #1906.
Should give higher performance for most models.
Spot check the ESS for various models.  The effect is evident in a 100-dimensional IID gaussian target, but other models should be compared.
None.
None user facing.
@syclik, @bob-carpenter 
Copyright: University of Warwick.
> Use delayed rejection transition in multinomial NUTS

- src/stan/lang/generator.hpp
- src/test/test-models/good/vector-zero.stan
- src/test/unit/lang/parser/var_decls_grammar_test.cpp
I couldn't run cpplint because insalling Anaconda and Python 3.x broke my build.
Generate explicit static cast to `VectorXd::Index` type for constructors of Eigen types to deal with ambiguity of `VectorXd(0)` call.
Allow zero sizes for row vectors, vectors, and matrices in Stan.
New model test compiles.
No.
Behavior now matches doc.
Anyone.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  Columbia University
> Index type for Eigen ctors, fixes #1909

- make/cpplint
- makefile
Adds a PYTHON2 make variable to control cpplint behavior.
Run `make cpplint PYTHON2=<some other python version>`
Removing the `RUN_CPPLINT` make variable.
Updated in the top level make help.
Anyone.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University.
> Fixes #1912. Adds PYTHON2 variable for use in cpplint

- src/stan/lang/ast_def.cpp
Removed use of `std::cout` from `ast_def.cpp`
Can't have `cout` in server code.
grep, check diffs
No.
no.
anyone.
> removed std::cout from ast_def.cpp

- src/stan/services/arguments/categorical_argument.hpp
Terminate when a categorical argument is mistakenly given a value, avoiding an infinite loop.  Resolves #1949.
Terminate argument parsing appropriately when categorical arguments are misspecified.
In Stan run the tests ```./runTests.py -j4 src/test/integration/services/arguments```.
In CmdStan run the test ```./runCmdStanTests.py src/test/interface/services/argument_configuration_test.cpp``` or try to run an example model,
```
make examples/bernoulli/bernoulli
cd examples/bernoulli
./bernoulli sample adapt=0
```
None.
Not user facing.
@syclik 
Copyright: University of Warwick.
- Documentation: …
> Terminate argument parsing when a categorical argument is mistakenly given a value

- src/stan/mcmc/hmc/xhmc/diag_e_xhmc.hpp
Fixed typo on header guard.
Proper header guarding.
In develop including src/stan/mcmc/hmc/xhmc/diag_e_xhmc.hpp twice should cause problems.  Now it will not.
None.
Not user facing.
@syclik @bob-carpenter 
Copyright: University of Warwick
> Fix header guard

- src/docs/stan-reference/language.tex
- src/stan/lang/ast.hpp
- src/stan/lang/ast_def.cpp
- src/stan/lang/generator.hpp
- src/stan/lang/grammars/functions_grammar_def.hpp
- src/stan/lang/grammars/program_grammar_def.hpp
- src/stan/lang/grammars/semantic_actions.hpp
- src/stan/lang/grammars/semantic_actions_def.cpp
- src/stan/lang/grammars/statement_2_grammar.hpp
- src/stan/lang/grammars/statement_2_grammar_def.hpp
- src/stan/lang/grammars/statement_grammar.hpp
- src/stan/lang/grammars/statement_grammar_def.hpp
- src/test/test-models/bad/break1.stan
- src/test/test-models/bad/break2.stan
- src/test/test-models/bad/break3.stan
- src/test/test-models/bad/break4.stan
- src/test/test-models/bad/break5.stan
- src/test/test-models/bad/break6.stan
- src/test/test-models/bad/break7.stan
- src/test/test-models/bad/break8.stan
- src/test/test-models/bad/continue1.stan
- src/test/test-models/bad/continue2.stan
- src/test/test-models/bad/continue3.stan
- src/test/test-models/bad/continue4.stan
- src/test/test-models/bad/continue5.stan
- src/test/test-models/good/break-continue.stan
- src/test/unit/lang/parser/break_continue_test.cpp
Add break and continue statements to Stan language.
More flexible control structures.
Unit tests for uses and illegal uses not in loops.  
No.
Language reference in the manual updated with behavior, examples, and BNF with side conditions.
Anyone.
> add break and continue statements

- src/stan/mcmc/hmc/nuts/base_nuts.hpp
- src/test/performance/logistic_test.cpp
- src/test/unit/mcmc/hmc/nuts/base_nuts_test.cpp
- src/test/unit/mcmc/hmc/nuts/softabs_nuts_test.cpp
- src/test/unit/mcmc/hmc/nuts/unit_e_nuts_test.cpp
Removes duplicate acceptance procedure in the default NUTS algorithm that was causing chains to push too far out into the tails.
Restores correctness of default NUTS algorithm.
The following model,
parameters {
real<lower=0, upper=1> x;
}
model {
x ~ uniform(0, 1);
}
should now return an actually uniform distribution.
Small changes to all default sampler output.
None.
@syclik, @bob-carpenter, @bgoodri 
Copyright: University of Warwick.
> Remove duplicate acceptance procedure, update tests

- src/stan/lang/ast.hpp
- src/stan/lang/ast_def.cpp
- src/stan/lang/function_signatures.h
- src/stan/lang/grammars/semantic_actions_def.cpp
- src/test/test-models/good/user-defined-lpdf-fun.stan
Allow user defined `_lpdf` and `_lpmf` functions with sampling notation.
Fixes bug.
Model and integration test.
No.
Fixes code to match existing doc.
> user-defined lpdf fixed, finishes #1944

- src/stan/lang/grammars/semantic_actions_def.cpp
- src/test/test-models/good/nullary-unconflicted.stan
Qualify namespace with `stan::math::` for built-in nullary functions.
Avoid name conflicts that currently arise if a variable in Stan is declared with the same name as a built-in and both are used.
New model test exercising everything.
No.
No, now the code matches the doc.
Anyone.
> qualify nullary fun names to avoid clash, finishes #1459

- src/docs/stan-reference/programming.tex
The Multivariate Regression Example included some optimizations but didn't include the, in my opinion, useful simplification recommended at the beginning of the Multiple Indexing and Range Indexing chapter. My substitution should probably be checked, as the order of variables in the "clunky assignment to a local variable" of the MRE and MIRI sections were different.
I assert no rights with regards to copyright & licensing.
> Manual: Added indexing-based simplification to Multivariate Regression Example

- makefile
`make clean-all` now removes all of the CVODES binaries.
None.
Updated in the default `make` target.
Anyone.
> make clean-all now removes built CVODES binaries

- src/stan/lang/grammars/semantic_actions.hpp
- src/stan/lang/grammars/semantic_actions_def.cpp
- src/stan/lang/grammars/term_grammar_def.hpp
- src/test/test-models/bad/prob-fun-args-no-bar.stan
- src/test/unit/lang/parser/redefine_prob_functions_test.cpp
Clarify error messages for probability functions.
Make it easier for users to understand error messages.
New model unit tests for new message.
No.
Not necessary.
Anyone.
> update error msg for , instead of | in prob funs, fixes #1940

- src/stan/model/indexing/rvalue_index_size.hpp
- src/test/unit/model/indexing/lvalue_test.cpp
- src/test/unit/model/indexing/rvalue_index_size_test.cpp
Add explicit test for indexes like `1:0` and set them to size zero.
Avoid 0 - 1 and large allocations if the result is used as unsigned.
Run unit new tests.
No.
Added note to user's guide section of manual under range indexing heading.
Anyone.
> explicit zeroing of descending indexes; fixes #1960

- src/test/unit/io/reader_test.cpp
Update to test code that stopped compiling with fix to stan-dev/math#382.
Fixes Stan test code.
Run tests.
None.
None.
Anyone.
> Updates test to be compatible with math#382

- src/docs/stan-reference/language.tex
- src/stan/lang/ast.hpp
- src/stan/lang/ast_def.cpp
- src/stan/lang/generator.hpp
- src/stan/lang/grammars/semantic_actions.hpp
- src/stan/lang/grammars/semantic_actions_def.cpp
- src/test/test-models/good/lower-trunc-discrete.stan
- src/test/unit/lang/ast_test.cpp
- src/test/unit/lang/generator_test.cpp
- src/test/unit/lang/parser/lower_trunc_adjust_test.cpp
- src/test/unit/lang/utility.hpp
Fixes off-by-one error in lower bound truncations for discrete distributions and updates manual to explain discrete vs. continuous translations.
Unit tests checking for all combinations of discrete/continuous distributions and built-in/lpdf/log probability function definitions.  Desired output explained and derived in the doc language section.
None.
Yes, updated manual.
Anyone. …
> Bugfix/2054 lower-bound discrete truncations off by 1

- src/stan/lang/grammars/semantic_actions_def.cpp
- src/test/unit/lang/parser/statement_grammar_test.cpp
Use "target +=" instead of "increment_log_prob()" in warning message for Jacobian.
Bring up to date with non-deprecated functions.
Changed the unit tests to match.
No.
N/A.
Anyone.
> Jacobian message uses target +=, fixes #2066

- make/tests
- src/stan/command/stanc_helper.hpp
- src/test/test-models/bad/stanc_helper.stan
- src/test/test-models/good/stanc_helper.stan
- src/test/unit/lang/stanc_helper_test.cpp
Allow stanc to read read-only files.
See summary.  Also added tests for stanc_helper.
_Help_:  Can't get the tests running in `src/test/unit/command` so dropped it in `src/test/unit/lang` instead.  I think it's a build issue.
_Help 2_:  If it matters, I can't get the right return code for an ill-formed model.  It returns illegal arguments.  But there wasn't any doc and I couldn't easily trace through the logic.
_Help 3_:  I created files from within C++ using a system call.  If there's a better way to do this through make or something, please fix.  I tried to code the test defensively, but may have failed.
Unit test.
none
n/a
@syclik  …
> use ifstream in stanc plus tests, fixes #1615

- src/docs/stan-reference/examples.tex
- src/docs/stan-reference/functions.tex
- src/stan/lang/function_signatures.h
- src/test/test-models/good/function-signatures/math/matrix/matrix_exp.stan
- src/test/unit/lang/parser/matrix_functions_test.cpp
I (@bob-carpenter) am just recreating this from PR #2092 of @charlesm93 with clean merge with new doc
Expose the matrix exponential function `matrix_exp` to Stan.
See Feature/issue 32 matrix exponential  for branch in Math.
Allow users to compute matrix exponentials.
Unit tests:
src/test/test-models/good/function-signatures/math/matrix/matrix_exp.stan
src/test/unit/lang/parser/matrix_functions_test.cpp
None.
function.text and programming.tex (section 20.6: Solving Linear ODEs with matrix exponential).
Metrum Research Group LLC …
> matrix_exp into language with doc, fixes #2043

- src/stan/lang/grammars/term_grammar_def.hpp
- src/test/test-models/good/var-ending-lpdf.stan
Fix bug in parser so that variables ending in `_lpdf` may be used in expressions.  It was assuming that anything ending in `_lpdf` was a log probability density function before.
New model checked into tests that parses with the patch but didn't parse before.
No.
No, behavior now matches doc.
anyone
> allow variables ending in _lpdf in expressions, fixes #2123

- make/tests
- src/docs/stan-reference/functions.tex
- src/stan/lang/function_signatures.h
- src/test/test-models/good/function-signatures/math/functions/choose.stan
Expose the `choose()` function to the Stan language and document it.
Allow people to use the `choose()` function in Stan programs, particularly in declarations like `vector[choose(K,2)] theta;`
Parse src/test/test-models/good/function-signatures/math/functions/choose.stan
None
Yes
Anyone
> Expose choose() function

- src/stan/model/indexing/lvalue.hpp
- src/test/unit/model/indexing/lvalue_test.cpp
Removes uses of `check_equal()` with more appropriate function `check_size_match()`.
Removes use of `check_equal()`.
Run 
```
./runTests.py src/test/unit/model/indexing/lvalue_test.cpp
```
The type of exception is now different. It is now a `std::invalid_argument` instead of `std::domain_error`.
The error message is slightly different too. An example old message:
```
vector[multi,...] assign sizes: ANON is 2, but must be equal to 11
```
The new message:
```
vector[multi,...] assign sizes: lhs (11) and ANON (2) must match in size
```
I think it's equally readable / unreadable. "ANON" will be filled in with the name of the right side.
Updated doxygen.
@bob-carpenter 
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or …
> Fixes #2148. Removes use of check_equal() with check_size_match()

- src/docs/stan-reference/appendices.tex
- src/docs/stan-reference/language.tex
- src/stan/lang/grammars/semantic_actions.hpp
- src/stan/lang/grammars/semantic_actions_def.cpp
- src/stan/lang/grammars/statement_grammar_def.hpp
- src/test/test-models/bad/print-void.stan
- src/test/unit/lang/parser/print_function_test.cpp
Disallow void arguments to `print()` statements.
Unit test with now unparseable model.
No.  It didn't compile before.
Clarified print section and also BNF in manual.
Anyone
> disallow void arguments to print, fixes #2168

- src/stan/io/dump.hpp
- src/test/unit/io/dump_test.cpp
fix issue #2179
Allow dump_reader to read zero arrays of integer (or double) that could be generated from `R`'s dump.  This would fix issue #2179 . 
Stan's dump interface can read data of the following format:
```
x <- integer(0)
y <- structure(integer(0), .Dim = c(2, 3))
z <- structure(double(0), .Dim = c(2, 3))
a <- double(1)
b <- structure(double(1), .Dim = c(1))
``` 
* see the added unit test
* build cmdstan with the new dump.hpp and run examples in #2179 
None.
See the doxygen comments in the code. 
@bob-carpenter @syclik  or anyone
Jiqiang Guo
By submitting this pull request, the copyright holder is agreeing to license the submitted work under the …
> dump_reader reads integer(x) as zero arrays

- src/stan/services/util/initialize.hpp
Adds a short message to the thrown `std::domain_error`. Interfaces which
are able to handle C++ exceptions may not be able to detect the
exception class; providing a message solves this problem.
Very minor change for PyStan (and similar interfaces unable to detect the type of the exception).
By submitting this pull request, I agree to license the submitted work under the following licenses:
> Add informational message to exception during initialization

- src/docs/stan-reference/functions.tex
- src/stan/lang/function_signatures.h
- src/test/test-models/good/function-signatures/math/matrix/to_matrix.stan
Expose the new to_matrix function from stan-math in the language.
A test has also been added that uses this in a model: src/test/test-models/good/function-signatures/math/matrix/to_matrix.stan
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Dual Space LLC
> Closes #2211. Expose to_matrix(vector v, int m, int n)

- src/stan/mcmc/hmc/nuts/base_nuts.hpp
- src/test/performance/logistic_test.cpp
- src/test/unit/mcmc/hmc/nuts/softabs_nuts_test.cpp
- src/test/unit/mcmc/hmc/nuts/unit_e_nuts_test.cpp
Removes initial state from the calculation of the average Metropolis acceptance probability.
Reduces the average Metropolis acceptance probability to be consistent with the average probability of accepting a jump to each new state in the HMC trajectory from the initial state.
Run unit tests or try it on your favorite model.
Should make adaptation a bit more robust by allowing a change in step size to more strongly affect the average acceptance probability.
None user facing.
Anyone.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  Columbia University. …
> Tweak average metro prob calc to not use initial state

- .travis.yml
Test dedupe - for now we run os x tests on Jenkins.
And as Travis is the slowest part of Stan builds, we'll cut off the OS X builds to save time
and get feedback to developers sooner. They're still covered by the Jenkins tests.
Dual Space LLC
> Test dedupe - for now we run os x tests on Jenkins.

- makefile
During the release the makefile wasn't corrected back to the old version - this fixes that. 
Might want to make the tag-* scripts more robust for future releases...
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Dual Space LLC
> fix sed failure on makefile

- makefile
http://discourse.mc-stan.org/t/new-error-on-stan-develop-during-windows-unit-tests/365/5
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Dual Space LLC
> Silence unused typedef warnings, new in gcc 4.9.

- src/docs/stan-reference/distributions.tex
- src/docs/stan-reference/examples.tex
- src/stan/lang/function_signatures.h
- src/test/test-models/good/function-signatures/distributions/rngs.stan
These are the changes to expose categorical_logit_rng to the Stan interfaces.
I changed how the example random numbers were generated in the changepoint model (Section 14.2). Tested it in cmdstan. Seemed to be producing the same histogram of changepoint dates.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): University of California Santa Barbara
> Added Stan hooks for categorical_logit_rng (feature 517)

- src/stan/services/util/initialize.hpp
- src/test/unit/services/util/initialize_test.cpp
Exceptions thrown in initialization are now reported.
Run 
```
./runTests.py src/test/unit/services/util/initialize_test.cpp 
```
or create a Stan program with a `reject()` statement. The tagged version won't output the error message.
None.
None.
Anyone.
Stan Group
> Fixes #2294. Reports errors in initialization

- src/stan/services/util/initialize.hpp
- src/test/unit/services/util/initialize_test.cpp
Stops sampling on errors that aren't `std::domain_error`s.
Stan programs that have `std::invalid_argument` or `std::out_of_range` errors are not recoverable. There's something broken in the Stan program and there's no point continuing. This pull request stops on errors that are not `std::domain_error`s.
For users, this should mask errors less by stopping early and making it look like a rejection.
There are additional tests here: `src/test/unit/services/util/initialize_test.cpp`
If you want to see different behavior, run this from your favorite interface:
```
parameters {
real<lower = 0, upper = 1> theta[1];
}
model {
theta[2] ~ normal(0, 1);
}
```
With this pull request, it stops almost immediately with this error message:
```
Unrecoverable error evaluating the log probability at the …
```
> Stop sampling on errors that aren't domain_errors

- src/docs/stan-reference/examples.tex
Not needed because this is just a doc change?
Typo fix.
Make example code from manual compile.
I was trying the example from the manual and editing the Stan file in RStudio which checks the syntax whenever I save. Here's before the edit.
```r
rstan:::rstudio_stanc("center-param.stan")
#> SYNTAX ERROR, MESSAGE(S) FROM PARSER:
#>   
#>   
#>   ERROR at line 33
#> 
#> 31:        for (n in 1:N)
#>   32:          x_beta_jj[n] = x[n] * beta[jj[n]]
#> 33:        y ~ normal(x_beta_jj, sigma);
#> ^
#>   34:      }
#> 
#> PARSER EXPECTED: ";"
#> Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  : 
#>   failed to parse Stan model 'center-param' due to the above error.
```
Here's after.
```r
rstan:::rstudio_stanc("center-param.stan")
#> center-param.stan is …
```
> missing semicolon in manual

- src/stan/mcmc/hmc/hamiltonians/softabs_metric.hpp
- src/stan/model/hessian.hpp
- src/stan/model/model_functional.hpp
Resolve `hessian()` to call O(N) reverse-mode version.
It was previously calling the O(N^2) forward-mode version because of const conflict instantiating reverse mode.
Tests still pass.  The resolution is guaranteed because of the functor type as the template parameter, which is only available for the reverse-mode Hessian calculation.
It'll be faster.
n/a
@betanalpha @syclik  …
> resolve hessian() in mcmc and model, fixes #2321

- src/docs/stan-reference/examples.tex
1/2 get rounded due to integer division
Changes only made to .tex file
- [NA] Run unit tests: `./runTests.py src/test/unit`
- [NA] Run cpplint: `make cpplint`
- [NA] Declare copyright holder and open-source license: see below
Fix bugs in example code in manual
> replace 1/2 in example code with 0.5

- src/stan/lang/parser.hpp
- src/test/test-models/bad/oneline-error.stan
- src/test/unit/lang/parser/error_messages_test.cpp
Automatically append a newline to every input program string.
Aloow error messages from the final line of a program if there is no end-of-line (`\n`) at the end of the file.
Added a new unit test for a one-liner with no end-of-line at end of file.  It fails in existing develop, but passes with this patch.
No.
n/a
anyone
> add eol to program strings; fixes #2359

- src/stan/lang/compile_functions.hpp
- src/stan/lang/compiler.hpp
> Fix typo in default filename for compile

- src/stan/lang/ast/node/fun_def.hpp
- src/stan/lang/grammars/semantic_actions_def.cpp
- src/stan/mcmc/hmc/xhmc/base_xhmc.hpp
Add `stan::math::` qualifier to `abs` in C++ code generated for a Stan program.
Remove ambiguity in g++.
Passes unit tests on integration server.
No.
n/a
> added stan::math:: qualifier to abs in generator

- .travis.yml
> gcc exhausts Travis memory if run in parallel

- src/stan/variational/advi.hpp
The display of the evidence lower bound is not precise enough, being limited to 1 significant digit. To be able to use those quantities to compare different models, more significant digits should be presented in the output (see also this discussion https://github.com/stan-dev/rstan/issues/272).
This is a sample of the current output:
```
Begin stochastic gradient ascent.
iter       ELBO   delta_ELBO_mean   delta_ELBO_med   notes 
100     -4e+07             1.000            1.000
200     -2e+07             0.966            1.000
300     -2e+06             4.786            1.000
400     -1e+06             3.630            1.000
500     -1e+05             5.368            1.000
```
This is how the output looks with the patch:
```
Begin stochastic gradient ascent.
iter             ELBO …
```
> Increase precision in the output of the ELBO values.

- makefile
See https://www.gnu.org/software/make/manual/html_node/Suffix-Rules.html
for reference.
This change massively reduces the number of steps run by make:
$ make -d | wc -l
5556
$ make -d | wc -l
411
The makefile line that is supposed to disable implicit rules is not correct, so implicit rules are actually not disabled, but are check at each make invocation.
By using .SUFFIXES (spelled correctly, see link to documentation), the number of rules checked is reduced as desired.
Compare the output of `make -d` before and after patch.
None.
None necessary.
Marco Colombo, University of Edinburgh
By submitting this pull request, the copyright holder is agreeing to …
> Use the correct syntax to disable implicit makefile rules

- src/docs/stan-reference/appendices.tex
Reference (manual) only.
The old grammar would contain `print("Hallo " "world!")`  but not `print("Hello ", "world!")`  while only the latter is actually accepted by stan. Should be a comment in #2336 . sorry, next time.
CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)
> fix Backus-Naur form gramma of print and reject

- src/test/unit/variational/eta_adapt_small_test.cpp
Just waht issue #2446 says---generalize test for Boost by replacing `==` with `>` in `ifdef`.
Allow us to upgrade Boost.  The PR for that in `stan-dev/math` is currently blocked:
https://github.com/stan-dev/math/pull/700
usual unit tests
no
n/a
> generalize boost version check in ADVI tests

- src/docs/stan-reference/distributions.tex
- src/stan/lang/function_signatures.h
- src/test/test-models/good/function-signatures/distributions/multivariate/discrete/ordered_logistic/ordered_logistic_log.stan
- src/test/test-models/good/function-signatures/distributions/multivariate/discrete/ordered_probit/ordered_probit_log.stan
- src/test/unit/lang/parser/distribution_functions_test.cpp
Update the manual, function signatures, and tests for the vectorised ordered logistic and probit distributions introduced in math prs: stan-dev/math/pull/638 stan-dev/math/pull/645
Allow usage of ordered logistic and probit distributions in stan
Visually inspect
N/A
Included in PR
> Update manual and function signatures for ordered logistic/probit

- Jenkinsfile
- src/test/performance/logistic_test.cpp
After a Jenkins master reboot a couple of days ago, the Jenkins Windows agent started being unable to delete its own workspace, showing messages like the one pasted below. These are often attributed to things like search indexing or anti-virus locking random files, but these are not the issue as reported by Unlocker (and the fact that the machine seems to have neither of these). For some reason, running `attrib` to remove the read-only and system attributes on the workspace before performing a delete or unstash seems to work. So here we are.
```
java.nio.file.AccessDeniedException: C:\Jenkins2\workspace\Stan_develop-3CVGV42HAM7J3BLI3M44PCR6M52FN6ZQ65IEZ6TOSHJURSBO2PPA\src\test\test-models\bad\read_only
at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
at …
```
> Work around Windows Jenkins failures

- src/stan/lang/generator/generate_function_arguments.hpp
Change the default argument of `pstream__` from 0 to `nullptr` now that we are using C++11
Make it easier to call `rstan::expose_stan_functions`
Call `rstan::expose_stan_functions` on a Stan program with a user-defined Stan function using the for-2.18 branch
None
None
> Use nullptr instead of 0

- src/stan/lang/rethrow_located.hpp
Add trivial default argument to `reader` in `rethrow_located`
Allow ancient Stan code to keep working when I update StanHeaders
I have been doing this in StanHeaders and it is fine.
Closes #2509 
None
> add default argument to reader

- src/stan/io/program_reader.hpp
Add `+ line` to error message
Keep people from throwing their laptops into a wall
Parse this
```
parameters {
#include foobar
}
```
or do it from rstan, which already contains this fix.
Closes #2507 
None
> add + line

- src/stan/lang/grammars/term_grammar_def.hpp
- src/test/test-models/good/algebra_solver_good.stan
- src/test/test-models/good/map_rect.stan
Add condition to `algebra_solver` and `map_rect` to allow symbols that use them as prefixes.  This is just a nofollow statement before the expectation in the grammar.
Allow the grammar to handle prefixes properly.
Added unit tests for both cases.
No.
Now matches doc.
> end of symbol for algebra_solver, map_rect, fixes #2502

- make/tests
Per stan-dev/math#779 the cvodes and idas libs are replaced by sundials. PR stan-dev/math#832 makes this update for the makefile of math lib. Similar changes need to be made for the makefile of cmdstan, rstan, etc. It suffices to replace LIBCVODES in makefile with LIBSUNDIALS.
Successful make of projects utilizing sundials functionalities.
Metrum Research Group, LLC
> update makefile to use sundials instead cvodes lib

- src/stan/lang/grammars/semantic_actions_def.cpp
- src/stan/lang/grammars/term_grammar_def.hpp
- src/test/test-models/bad/ode/adams/bad_adams_control_function_return.stan
- src/test/test-models/bad/ode/adams/bad_control_function_return.stan
- src/test/test-models/bad/ode/adams/bad_fun_type.stan
- src/test/test-models/bad/ode/adams/bad_fun_type_control.stan
- src/test/test-models/bad/ode/adams/bad_t0_var_type.stan
- src/test/test-models/bad/ode/adams/bad_t0_var_type_control.stan
- src/test/test-models/bad/ode/adams/bad_t_type.stan
- src/test/test-models/bad/ode/adams/bad_t_type_control.stan
- src/test/test-models/bad/ode/adams/bad_theta_type.stan
- src/test/test-models/bad/ode/adams/bad_theta_type_control.stan
- src/test/test-models/bad/ode/adams/bad_ts_type.stan
- src/test/test-models/bad/ode/adams/bad_ts_type_control.stan
- src/test/test-models/bad/ode/adams/bad_ts_var_type.stan
- src/test/test-models/bad/ode/adams/bad_ts_var_type_control.stan
- src/test/test-models/bad/ode/adams/bad_x_int_type.stan
- src/test/test-models/bad/ode/adams/bad_x_int_type_control.stan
- src/test/test-models/bad/ode/adams/bad_x_type.stan
- src/test/test-models/bad/ode/adams/bad_x_type_control.stan
- src/test/test-models/bad/ode/adams/bad_x_var_type.stan
- src/test/test-models/bad/ode/adams/bad_x_var_type_adams_control.stan
- src/test/test-models/bad/ode/adams/bad_x_var_type_control.stan
- src/test/test-models/bad/ode/adams/bad_y_type.stan
- src/test/test-models/bad/ode/adams/bad_y_type_control.stan
- src/test/test-models/good/integrate_ode_adams.stan
- src/test/test-models/good/ode_good.stan
- src/test/test-models/good/parser-generator/ode_control.stan
- src/test/unit/lang/parser/integrate_ode_deprecation_test.cpp
- src/test/unit/lang/parser/ode_test.cpp
With https://github.com/stan-dev/math/issues/734 we are ready to provde Adams-Moulton integrator to Stan language. The process is identical to `rk45` and `bdf` integrators, as the function signature as well as ODE functor signature remain the same.
Support `integrate_ode_adams` function as the third ODE solver in Stan.
Unit tests and model tests.
n/a
Metrum Research Group, LLC
> integrate_ode_adams in Stan

- src/stan/lang/function_signatures.h
- src/test/test-models/good/function-signatures/math/functions/log_mix.stan
Adds function signatures and instantiation tests for the extended log_mix functions added in stan-dev/math#664 and stan-dev/math#751
The new signatures are:
```
Available argument signatures for log_mix:
log_mix(real, real, real)
log_mix(real[], real[])
log_mix(real[], vector)
log_mix(real[], row vector)
log_mix(real[], vector[])
log_mix(real[], row vector[])
log_mix(vector, real[])
log_mix(vector, vector)
log_mix(vector, row vector)
log_mix(vector, vector[])
log_mix(vector, row vector[])
log_mix(row vector, real[])
log_mix(row vector, vector)
log_mix(row vector, row vector)
log_mix(row vector, vector[])
log_mix(row vector, row vector[])
```
Expose the new functions for use in Stan
Instantiation tests for new signatures have been added to the test for the current (ternary) signature
N/A …
> Add new log_mix signatures and unit tests

- src/stan/lang/function_signatures.h
- src/test/test-models/good/function-signatures/math/matrix/matrix_exp_multiply.stan
- src/test/test-models/good/function-signatures/math/matrix/scale_matrix_exp_multiply.stan
- src/test/unit/lang/parser/matrix_functions_test.cpp
This PR address #2539, allowing
```Stan
matrix_exp_multiply(matrix A, matrix B);
scale_matrix_exp_multiply(real t, matrix A, matrix B);
```
in Stan language.
```Stan
matrix_exp_multiply(matrix A, matrix B);
scale_matrix_exp_multiply(real t, matrix A, matrix B);
```
for `exp(A)B` and `exp(tA)B`, respectively.
unit tests
n/a
#2547
Metrum Research Group, LLC
> Feature 2539 matrix exp mult

- src/docs/stan-reference/functions.tex
documenting #2539 .
docs for two new functions `matrix_exp_multiply` & `scale_matrix_exp_multiply`.
doc
n/a
Metrum Research Group, LLC
> doc matrix_exp_multiply

- src/docs/stan-reference/examples.tex
- src/docs/stan-reference/functions.tex
- src/stan/lang/function_signatures.h
- src/test/test-models/good/function-signatures/math/matrix/qr_thin_Q.stan
- src/test/test-models/good/function-signatures/math/matrix/qr_thin_R.stan
- src/test/unit/lang/parser/matrix_functions_test.cpp
Expose `qr_thin_Q()` and `qr_thin_R()` to the Stan language
Allow users to use `qr_thin_Q()` and `qr_thin_R()`.
Fixes #2560 .
Run tests under `src/test/test-models/good/function-signatures/math/matrix/`
Uses less RAM than fat QR decomposition
Yes
> expose qr_thin_{Q,R}

- src/stan/services/util/mcmc_writer.hpp
- src/test/unit/services/util/mcmc_writer_test.cpp
Fixes the behavior in `mcmc_writer` so that when there's an exception thrown in the model's generated quantities block, it writes out the parameter values and `NaN` for any generated quantity.
Changes the behavior so that the number of draws is the number of iterations.
There's an updated unit test that verifies that the right terms are `NaN`.
If you run the model in issue #2568, there are now the right number of posterior draws with the rejections forcing all of the generated quantities to output `NaN`.
This fixes weird behavior of differing chain lengths.
This may affect the interfaces if they aren't accepting `NaN` as a valid value.
None.
Generable
By …
> Fixes #2568. Updates the code so on exception in generated quantities, all generated quantities are NaN

- Jenkinsfile
This will be sort of a moot point once we move to a monorepo, but..
> Add workaround for empty params in Jenkins job triggering

- src/test/performance/logistic_test.cpp
New parameterisation of inv_logit (math pull stan-dev/math#889) to avoid underflow causes the logistic performance test to return slightly different values (as a result of no longer underflowing).
Allow new parameterisation to pass,
N/A
N/A
N/A
> Update expected values for performance test

- src/stan/lang/grammars/semantic_actions_def.cpp
- src/test/unit/lang/parser/assignment_test.cpp
- src/test/unit/lang/parser/expression_grammar_test.cpp
- src/test/unit/lang/parser/if_else_deprecation_test.cpp
- src/test/unit/lang/parser/lkj_cov_deprecation_test.cpp
- src/test/unit/lang/parser/replace_log_funs_test.cpp
- src/test/unit/lang/parser/statement_grammar_test.cpp
Changed messages from parser so that messages prefaced with "Warning" and "Warning (non-fatal)" are now prefaced with "Info" instead.
see issue #2608 
unit tests stan/lang/parser
N/A
N/A
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  Columbia University
> Change parser messages to avoid word "Warning" - use "Info" instead

- src/stan/analyze/mcmc/compute_effective_sample_size.hpp
To allow including the header in multiple compilation units.
see https://github.com/stan-dev/stan/issues/2615
Copyright: Tal Kedar
> add inline to the declaration of compute_effective_sample_size(...) 

- .travis.yml
This should fix the broken Travis build.
Here are the different things that are being done in this PR:
1. changing make/local to set `CXX` instead of `CC`.
2. Changing the `-stdlib=libc++` to be added to `CXXFLAGS_OS` instead of `LDFLAGS_OS`. Some of these failures occurred because the `LDFLAGS_OS` are only added to the linking step, but not the compilation step (from `.cpp` to `.o`). It's needed there.
3. Adding `-pthread` to `CXXFLAGS_OS` for `g++-4.9`. I looked at the logs and it's in the build options that work pre-merge of the PR.
4. Changing the dependency generation flags. Perhaps this should be based on compiler (for a future issue): `DEPFLAGS_OS = -M -E`.
Fix travis.
Hopefully it'll pass. I'll put up a link when it does.
None.
None.
Please list the copyright holder for the work …
> Fixing broken travis build

- src/stan/mcmc/sample.hpp
Added explicit default copy and move c'tor and assignment operator, and made the d'tor default (instead of an explicit no-op), to enable move semantics for stan::mcmc::sample
Addresses issue #2646.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Tal Kedar
> move semantics for stan::mcmc::sample

- src/stan/mcmc/hmc/hamiltonians/dense_e_metric.hpp
- src/test/unit/mcmc/hmc/hamiltonians/dense_e_metric_test.cpp
- [ x] Run unit tests: `./runTests.py src/test/unit`
- [ x] Run cpplint: `make cpplint`
- [x ] Declare copyright holder and open-source license: see below
Fixed the bug described in https://github.com/stan-dev/stan/issues/2671
The maths is correct. I am unsure what the current tests are testing. Maybe they should be improved.
None
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): University of Toronto
> [WIP] incorrect sampling from mulivariate normal specified by its precision matrix

- Jenkinsfile
`aggregatingResults` - Ties the results together, so we have tied together the gcc4 & clang in the same UI. Can be disabled by setting it to `false`
`blameDisabled` - Determines who is the author of an issue. ( See https://github.com/jenkinsci/warnings-ng-plugin/blob/master/doc/Documentation.md#source-code-blames-for-git-projects )
`qualityGates` - Quality gates let you modify Jenkins' build status so that you immediately see if the desired quality of your product is met ( See https://github.com/jenkinsci/warnings-ng-plugin/blob/master/doc/Documentation.md#quality-gate-configuration )
`healthy` - Health report of the project ( See https://github.com/jenkinsci/warnings-ng-plugin/blob/master/doc/Documentation.md#health-report-configuration )
`referenceJobName` - References the baseline, …
> Updated Jenkinsfile to support new warnings plugin

- src/stan/io/array_var_context.hpp
- src/stan/io/stan_csv_reader.hpp
- src/stan/mcmc/hmc/integrators/expl_leapfrog.hpp
- src/stan/mcmc/sample.hpp
- src/stan/model/indexing/lvalue.hpp
- src/stan/model/model_functional.hpp
- src/test/unit/services/sample/standalone_gqs_test.cpp
The methods added using Eigen's plugin system in PR stan-dev/math#1216 cause compilation errors in the header and unit tests for Stan if any Eigen headers are included prior to ```math/prim/mat/fun/Eigen.hpp```.
This PR updates the minimum number of headers needed to allow these tests to pass with the new methods.
No compilation errors
Tests compile and pass
N/A
N/A
> Issue 2755 - Update Eigen includes to allow compilation with new plugin methods

- src/stan/lang/generator/generate_model_typedef.hpp
- src/test/unit/lang/generator/generate_new_model_test.cpp
Added ifdef around new_model to prevent it being compiled in R.
Let R have multiple Stan models in a single translation unit.
New unit test.
No.
n/a
> add ifdef for R new_model, fixes #2797

- src/stan/mcmc/hmc/hamiltonians/dense_e_point.hpp
- src/stan/mcmc/hmc/hamiltonians/diag_e_point.hpp
- src/stan/mcmc/hmc/hamiltonians/ps_point.hpp
- src/test/unit/mcmc/hmc/hamiltonians/ps_point_test.cpp
fast_vector_copy and fast_matrix_copy of ps_point were removed. Those functions were doing a resize on the lhs vector and then a `memcopy` in. I'll do a speedtest but I'd be suprised if that beat default behavior
Code removal
Performance tests tbd
Hopefully none!
> [WIP] Removed fast copy funcs from ps_point and dependents

- .travis.yml
This PR should fix the travis issue we are having since the introduction of TBB. Lets first wait if it fixes it, but it should.
Sidenote: Not sure we even need Travis at all anymore. See https://github.com/stan-dev/cmdstan/issues/728#issuecomment-532400217
But that is certainly not my call to make.
fix travis
/
/
> Travis fix: bump clang version from 3.8 to 6.0

- src/stan/lang/generator/expression_visgen.hpp
Fixes the compiler to work with the corrected signature of integrate_1d from stan-dev/math#933.
> Fix tests for stan-dev/math#933.

- src/stan/mcmc/stepsize_adaptation.hpp
- src/stan/mcmc/stepsize_adapter.hpp
- src/stan/mcmc/stepsize_covar_adapter.hpp
- src/stan/mcmc/stepsize_var_adapter.hpp
Add `const noexcept` accessors to the stepsize adaptation class (for accessing delta, kappa, ...) and in the various adapters (for accessing the adaptation object).
No functional change for Stan users.
Allow developers to query the adaptation parameters in contexts where it's natural to have a `const` sampler (logging, serialization, ...).
N/A (trivial)
None. 
N/A (trivial)
Tal Kedar
> Stepsize adaptation and adapters const accessors (NFC)

- src/stan/variational/advi.hpp
- src/stan/variational/families/normal_fullrank.hpp
- src/stan/variational/families/normal_meanfield.hpp
This replaces the few existing uses of `stan::math::domain_error` with `stan::math::throw_domain_error`.
Existing tests should run correctly.
None.
Not needed.
Marco Colombo
> Use throw_domain_error instead of stan::math::domain_error

- src/stan/mcmc/chains.hpp
- src/test/unit/mcmc/chains_test.cpp
This changes the `Eigen::Matrix<std::string, Dynamic, 1>` containers to `std::vector<std::string>` for `stan::mcmc::chains`, as suggested in the first point of #1479. 
Current tests should pass.
It's not clear to me if other interfaces use this header directly (at least rstan shouldn't be affected, from by inspection), and what guarantees we make about not chaning this.
The only potentially breaking change is that now `param_names()` returns a `const std::vector<std::string>&` rather than `const Eigen::Matrix<std::string, Dynamic, 1>&`, which means that indexing the resulting container will have to use `operator[]` instead of `operator()`.
Marco Colombo
By …
> Replace Eigen vectors of strings with std::vector<std::string>

- .travis.yml
This PR will force Travis to use `trusty` instead of the now default `xenial`.
To add a bit of context, Travis started slowly rolling out `xenial` as the default distro a while ago, see thread [here](https://changelog.travis-ci.com/xenial-as-the-default-build-environment-99476) therefore it broke our pipeline.
See where stan failures were reported, thread [here](https://discourse.mc-stan.org/t/jenkins-updates-issues-requests/12426/3?u=serban-nicusor).
> Making sure distro is set as trusty for clang-6 in travis

- src/stan/variational/print_progress.hpp
https://github.com/stan-dev/math/pull/1572 in Stan Math will remove the scal,mat,arr folder in the /err folder in fwd, mix, rev and prim. This PR fixes replaces the includes of two /err headers with the include of err.hpp.
This PR will be teste with the respective Math PR branch so both PRs have to be merged together in order to keep develop stable.
> Fix includes of /err from Stan Math after flattening

- src/stan/mcmc/hmc/hamiltonians/softabs_metric.hpp
- src/stan/model/grad_tr_mat_times_hessian.hpp
- src/stan/model/gradient_dot_vector.hpp
- src/stan/model/hessian.hpp
- src/stan/model/hessian_times_vector.hpp
The flattening of mix happening in https://github.com/stan-dev/math/pull/1584 replaces `stan/math/mix/mat.hpp` with `stan/math/mix.hpp`, so this is required alongside those changes.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): 
Marco Colombo
> Fix mix includes for flatten

- src/stan/model/gradient.hpp
- src/stan/model/log_prob_grad.hpp
- src/stan/model/log_prob_propto.hpp
- src/test/unit/model/indexing/lvalue_test.cpp
The flattening of rev happening in stan-dev/math#1593 replaces stan/math/rev/mat.hpp with stan/math/rev.hpp, so this is required alongside those changes.
> Fix include rev flatten

- Jenkinsfile
This fix changes how Windows tests are run such that the Math libs are built first, with a single thread. This is in order to prevent errors such as this one: https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/downstream_tests/1162/pipeline
Similar change was done in Stan Math in https://github.com/stan-dev/math/pull/1594
> Jenkins Windows fix - build math libs first

- src/test/test-models/good/logistic_regression_reg_horseshoe.stan
Adds the logistic regression with reguralized horseshoe prior from Aki Vehtari, Juho Piironen. This is used to test the Eigen expression return bug (see https://github.com/stan-dev/math/pull/1644)
Rok Češnovar
(I am not the author of the test model, but I have [the permission from the authors](https://github.com/stan-dev/math/pull/1644#issuecomment-579128098) so I wrote them as copyright holders also. I dont know if this is needed, but is included anyways)
Aki Vehtari
Juho Piironen …
> Add logistic regression with reg. horseshoe prior to test eigen expression returns

- src/stan/model/indexing/deep_copy.hpp
- src/stan/model/indexing/lvalue.hpp
- src/stan/model/indexing/rvalue.hpp
- src/test/test-models/good/compound-assign/indexed_expr_divide_equals.stan
- src/test/unit/model/indexing/lvalue_test.cpp
- src/test/unit/model/indexing/rvalue_test.cpp
This allows `rvalue` and `assign` to take in generic eigen expressions. This uses a `const` [`Eigen::Ref`](https://eigen.tuxfamily.org/dox/classEigen_1_1Ref.html) on the rhs of `assign` and the input to `rvalue` so that eigen expressions sent into rvalue that need row or column access will first be evaluated. This allows `Eigen::Matrix` inputs to avoid a copy while eigen expressions will be evaluated 
This PR also makes one specialization for the case of `A[, col_index]` for grabbing a column of a matrix. It feels like this should be a regular thing people do and since we do col major index it feels like an easy slice to grab with `A.col()`
Inputs to `rvalue` and `assign` can be more complex eigen expressions
Additional tests have been added to rvalue_test and lvalue_test that can be run …
> Allow rvalue and assign to accept eigen expressions

- src/test/test-models/good/int_overloads.stan
- [x ] Declare copyright holder and open-source license: see below
Adding a model that will test fun(int) and fun(real) for all functions that mirror the std:: cmath functions. 
This is added to test the changes in https://github.com/stan-dev/math/pull/1765
> std:: int overloads test model

- Jenkinsfile
This PR removes code that was moved into the Shared Libraries while also fixing a bug reported in 
https://github.com/stan-dev/math/issues/1773
> Moved verify changes from Jenkinsfile to Shared Libraries.

- src/stan/lang/generator/generate_usings.hpp
This is an alternate fix to https://github.com/stan-dev/math/pull/1810.
Work in progress, don't merge. It shouldn't work with mingw as it is anyway.
> [WIP] Add `using std::pow` to model code generator (Issue #1809 in math)

- src/stan/analyze/mcmc/compute_effective_sample_size.hpp
- src/stan/analyze/mcmc/compute_potential_scale_reduction.hpp
- src/stan/io/array_var_context.hpp
- src/stan/io/dump.hpp
- src/stan/io/reader.hpp
- src/stan/mcmc/hmc/base_hmc.hpp
- src/stan/mcmc/hmc/nuts/base_nuts.hpp
- src/stan/mcmc/hmc/nuts_classic/base_nuts_classic.hpp
- src/stan/mcmc/hmc/static/base_static_hmc.hpp
- src/stan/mcmc/hmc/static_uniform/base_static_uniform.hpp
- src/stan/mcmc/hmc/xhmc/base_xhmc.hpp
- src/stan/model/indexing/lvalue.hpp
- src/stan/model/indexing/rvalue.hpp
- src/stan/model/model_header.hpp
- src/stan/optimization/bfgs.hpp
- src/stan/optimization/bfgs_linesearch.hpp
- src/stan/optimization/lbfgs_update.hpp
- src/stan/services/util/initialize.hpp
This is part of a wider cleanup to address stan-dev/cmdstan#863
Replaces: 
- `boost::math::isfinite` with `std::isfinite`
- changes `BOOST_THROW_EXCEPTION(std::invalid_argument(msg));` to `throw std::invalid_argument(msg);`
- boost::math::isnan(h) with std::isnan(h) 
- disable_if with std::enable_if
- cleans up unused headers
> Cleanup the use of boost::

- make/cpplint
Updates `cpplint` so `python 2` is no longer required.
This change ONLY makes sense when https://github.com/stan-dev/math/pull/1871 has been merged.
No more warnings about `python 2` while running `cpplint`
`make cpplint`
VERY dependent on this:
https://github.com/stan-dev/math/pull/1871
N/A
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Rohit Goswami <rg0swami[at]yahoo.com>
> cpplint: Harmonize with stan-dev/math

- src/stan/services/sample/fixed_param.hpp
- src/stan/services/util/initialize.hpp
- src/stan/services/util/run_adaptive_sampler.hpp
- src/stan/services/util/run_sampler.hpp
- src/stan/variational/advi.hpp
Fixes #2921 by replacing clock_t with std::chrono::steady_clock
> Replace clock_t with std::chrono

- src/stan/io/stan_csv_reader.hpp
Currently, CSV reader always reads in the header and then prettifies the indexed names:
y.1 becomes y[1], y.1.1 becomes y[1,1] and so on. 
For standalone generated quantities in cmdstan where we read in a CSV we want to have the option of not prettifying: this caused a bug of matching y.1 and y[1] which threw a mismatch.
This PR adds the option of not prettifying and is a prerequisite for https://github.com/stan-dev/cmdstan/pull/900 that will fix https://github.com/stan-dev/cmdstan/issues/841
Rok Češnovar, Univ. of Ljubljana
- Code: …
> Bugfix/841-cmdstan: Add option of reading in csv without fixing indexed names

- src/stan/model/log_prob_grad.hpp
- src/stan/model/log_prob_propto.hpp
Fixes #2936 to make sure memory is recovered for log_prob_grad.
> Add recover_mem to log_prob_grad

- src/stan/mcmc/hmc/base_hmc.hpp
- src/test/unit/mcmc/hmc/base_hmc_test.cpp
Add a const accessor to `_z` in `src/stan/mcmc/hmc/base_hmc.hpp`
Allow access in const contexts, useful for code integration with Stan as a library.
N/A
Shouldn't be any.
N/A
K2DQ, LLC
> [NFC] base_hmc const accessor to _z

- src/stan/io/array_var_context.hpp
- src/stan/io/chained_var_context.hpp
- src/stan/io/dump.hpp
- src/stan/io/empty_var_context.hpp
- src/stan/io/random_var_context.hpp
- src/stan/io/validate_dims.hpp
- src/test/unit/io/array_var_context_test.cpp
Fixes #2948 
array_var_context used by rstan and pystan has an empty validate_dims function: https://github.com/stan-dev/stan/blob/develop/src/stan/io/array_var_context.hpp 
This PR adds the code from https://github.com/stan-dev/stan/blob/develop/src/stan/io/dump.hpp#L773
and tests.
In order to verify comment out the added code in validate_dims and run the array_var_context_test. It will segfault.
Rok Češnovar, Univ. of Ljubljana …
> Add validate_dims in array_var_context

- src/stan/mcmc/hmc/hamiltonians/base_hamiltonian.hpp
- src/stan/mcmc/hmc/hamiltonians/dense_e_metric.hpp
- src/stan/mcmc/hmc/hamiltonians/ps_point.hpp
- src/stan/mcmc/hmc/integrators/impl_leapfrog.hpp
- src/stan/model/indexing/deep_copy.hpp
- src/stan/model/indexing/rvalue_return.hpp
- src/stan/optimization/bfgs_update.hpp
- src/stan/optimization/lbfgs_update.hpp
- src/stan/optimization/newton.hpp
- src/stan/services/sample/standalone_gqs.hpp
- src/stan/services/util/create_unit_e_dense_inv_metric.hpp
- src/stan/services/util/read_diag_inv_metric.hpp
- src/test/unit/services/instrumented_callbacks.hpp
- src/test/unit/util.hpp
In some places, we directly include `<Eigen/...>` files. That is discouraged due to our implementations of .val() and .adj() in Math. This PR cleans that up in the Stan repo.
> cleanup includes of Eigen/*

- Jenkinsfile
- make/tests
- src/test/integration/standalone_functions_test.cpp
This PR does a few minor things: 
- after https://github.com/stan-dev/stanc3/pull/524 we can run standalone functions tests in this repo with stanc3. This PR fixes the makefile logic to use stanc3 for those tests as well. stanc2 is no longer used for tests in /stan
- adds a test that uses a standalone function compiled with stanc. Previously we only checked that the models compile.
- changes the Windows Integration Jenkins stage to only run on merges to develop/master. This test can run for 4 hours if used on a non-AWS machine and the likelihood of Unix integration tests passing and this one failing are slim.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Rok Češnovar, Uni. of Ljubljana
By submitting …
> Use stanc3 for standalone functions tests and run Win integration tests on merges only

- Jenkinsfile
Fixes #2971 by only running Mac integration tests on merges. The chances of Linux integration tests passing and Mac integration tests failing are so slim in my opinion, it make sense to only run this on merges. We still do want this tested.
The other change is that the pipeline will stop immediately once a stage fails (not running other stages until the end).
Rok Češnovar, Uni. of Ljubljana
> Optimize Jenkins pipeline

- src/stan/model/indexing/lvalue.hpp
- src/stan/model/indexing/rvalue.hpp
- src/test/unit/model/indexing/rvalue_test.cpp
This is the `rvalue()` func version of #2964 for doing efficient slices of eigen matrices.
Should hopefully make indexing like 1:N etc more useful. This will mainly give a performance bump once we are passing around expressions.
Tests have been added to `rvalue_test.cpp`
```
./runTests.py -j4 ./src/test/unit/model/indexing/
```
Docs updated for all overloads for indexing 
> Add overloads of rvalue() for efficient slicing

- src/stan/model/indexing/lvalue.hpp
- src/stan/model/indexing/rvalue.hpp
Quick fix pr, there were three rvalue/lvalue functions that we should be checking the rows and not the columns
> fix range checks for the row slicing lvalue rvalue

- src/stan/io/reader.hpp
- src/test/unit/io/reader_test.cpp
This adds functions in reader that allow it to output a `var<matrix>`
This will be used by the stan compiler when reading out `var<matrix>` types in log_prob, write_array, etc
Tests were added to check that io works for the normal path, zero sized path, and when the reader has a `double` type (which for `var<matrix>` function we need to return back a `matrix<double>`
```
./runTests.py ./src/test/unit/io/reader_test
```
This currently only supports standard io and not lower bound, upper bound, correlation matrices, etc. type vars. We need a few things in stan math before we can support all those
Docs added for each new function
By submitting …
> allow reader to read out var<matrix> types

- Jenkinsfile
Moving Jenkins `Integration Windows` step to run only on AWS EC2 instaces.
> Moving Integration Windows step to run only on AWS EC2

- src/stan/model/indexing/index.hpp
- src/stan/model/indexing/index_list.hpp
- src/stan/model/indexing/rvalue_at.hpp
- src/stan/model/indexing/rvalue_index_size.hpp
This removes constexpr from indexing related functions and classes as mingw's gcc 4.9.3 does not fully support them.
> Remove constexpr from indexing classes/functions as mingw's gcc 4.9 cannot support it

- RELEASE-NOTES.txt
This adds the missing `v2.25.0` tag, fixes `git describe`, and updates the release notes. This is done by merging the the `release/v2.25.0` branch and resolving the conflicts (just updating the release notes and merging the tags). For the future releases, everything should be updated with a tag added in the `develop` branch before creating a new `release/vX.Y.Z` branch.
**Since I can't push tags in a pull request, a dev needs to merge the tags from `release/v2.25.0` and `git push --follow-tags`.**
**Before:**
`git describe`
> v2.24.0-347-gd8d52cd28
**After:**
`git describe`
> v2.25.0-252-ge283d0b86
This may also be used in the versioning of the `develop` branch, following https://github.com/stan-dev/stan/pull/2990 and [this discussion](https://discourse.mc-stan.org/t/versioning-after-relea …
> Fix tags / git-describe, and update release notes

- makefile
- src/stan/io/array_var_context.hpp
- src/stan/io/chained_var_context.hpp
- src/stan/io/dump.hpp
- src/stan/io/empty_var_context.hpp
- src/stan/io/random_var_context.hpp
- src/stan/io/reader.hpp
- src/stan/io/validate_dims.hpp
- src/stan/io/var_context.hpp
- src/stan/io/writer.hpp
- src/stan/lang/generator/generate_cpp.hpp
- src/stan/lang/generator/generate_model_compile_info_method.hpp
- src/stan/model/model_base.hpp
- src/test/unit/io/array_var_context_test.cpp
- src/test/unit/model/model_base_crtp_test.cpp
- src/test/unit/model/model_base_test.cpp
This makes `StanHeaders 2.26.0` (https://github.com/stan-dev/rstan/pull/887) compatible with both `Stan 2.26 & 2.21`, basically addressing backward compatibility for CRAN submission. It introduces `USE_STANC3` macro to branch changes specific to Stan 2.26 that cannot be supported by the older version of `stanc` transpiler.
Building `rstan` & its dependencies (e.g., `rstanarm`) is successful both versions of `Stan`.
N/A
`StanHeaders` is now compatible with all versions of `Stan`, including CRAN and the development version.
- unit tests pass (to run, use: `./runTests.py test/unit`)
- header checks pass, (`make test-headers`)
- dependencies checks pass, (`make test-math-dependencies`)
- docs build, (`make doxygen`)
- code passes the built in [C++ …
> StanHeaders: compatibility for both Stan 2.26 and 2.21

- src/test/unit/io/writer_test.cpp
This reverts the infinite bounds checks PR as we rewrote them in Stan to support the bounds checking behavior for pos/neg infinity. This branch needs to do the dual merge thing to have this and the math branch [#2373](https://github.com/stan-dev/math/pull/2373) at the same time
> Revert "Feature/bounds no inf"

- Jenkinsfile
This PR refactors the tests: 
- Integration tests on Unix OSes now compiles using cmdstan's tests
On Linux this is a lot faster (20min instead of 1h40min). On Mac its a bit faster (45min vs 1h5min). On Windows it seems to be slower so its left as is.
- Mac/Windows Unit tests are run on merges to develop/master: 
- Mac/Windows Unit tests can also be run on request
> Stan tests refactor

- src/stan/model/model_header.hpp
We forgot to add the header includes for the serializer/deserializer in the `model_header.hpp`
Have the model know it can use these two classes
> adds serializer headers to model header

- Jenkinsfile
This removes the expression tests from stan-dev/stan. It should wait on https://github.com/stan-dev/math/pull/2419 which moves expressions tests back to Math.
Issue for this is: https://github.com/stan-dev/math/issues/2425
> Removed expressions tests

- src/stan/io/serializer.hpp
- src/test/unit/io/serializer_test.cpp
For the refactoring of `transform_inits()` in the compiler we actually need the free functions to be in the serializer. See the discussion [here](https://github.com/stan-dev/stanc3/pull/872#issuecomment-815128608) for more info.
Allow the serializer to perform the free'ing of constrained variables
Tests were added to do the same checks as the `deserializer`'s free tests
```bash
./runTests.py ./src/test/unit/io/serializer_test.cpp
```
Documentation for each of the free functions in `serializer` …
> Adds free function tests for serializer

- Jenkinsfile
This PR will remove the extremely large test models from the regular Integration test models batch. 
The models being removed:
- `distributions/univariate/continuous/exp_mod_normal`
- `distributions/univariate/continuous/pareto_type_2`
- `distributions/univariate/continuous/skew_normal`
- `distributions/univariate/continuous/student_t`
- `distributions/univariate/continuous/wiener`
They are being removed from being used in every PR because they represent 70%+ of execution time for these tests and do not add a lot of test coverage, if any.
These models are simple but huge. They test that all different signatures compile. And because these distributions have many arguments
the models are huge. They thus also consume a lot of RAM which limits the parallel setting we can use (we quickly run …
> Refactor Integration tests

- src/stan/model/indexing/assign.hpp
- src/stan/model/indexing/assign_varmat.hpp
- src/test/unit/model/indexing/assign_varmat_test.cpp
- src/test/unit/model/indexing/rvalue_varmat_test.cpp
- src/test/unit/model/indexing/util.hpp
This fixes the `assign()` errors from https://github.com/stan-dev/stanc3/pull/898 for doing `var<Matrix> = Eigen::Matrix<double>`. Combining this with https://github.com/stan-dev/math/pull/2535 removed the errors on the sample of test models I tried out in the stanc test suite that were previously failing.
Explicit paths had to be added in the callbacks for assignment using `index_uni` and `index_multi`. For all the other functions I wrote a `assign_impl()` function that is just `A = B` for all cases besides `var<Matrix> = Eigen::Matrix<double>`. For that case we do a procedure to update the var values and then in a reverse pass callback put back the old values and reset the adjoints to zero.
Allow assignment from `Eigen::Matrix<double>` to `var<Matrix>` in the stanc generated C++.
All …
> Fix: Eigen double to matrix var assignment

- src/stan/model/indexing.hpp
- src/stan/model/indexing/access_helpers.hpp
- src/stan/model/indexing/assign.hpp
- src/stan/model/indexing/assign_varmat.hpp
- src/stan/model/indexing/index.hpp
- src/stan/model/indexing/rvalue.hpp
- src/stan/model/indexing/rvalue_varmat.hpp
- src/test/unit/model/indexing/assign_test.cpp
- src/test/unit/model/indexing/assign_varmat_test.cpp
- src/test/unit/model/indexing/deep_copy_test.cpp
- src/test/unit/model/indexing/index_test.cpp
- src/test/unit/model/indexing/rvalue_index_size_test.cpp
- src/test/unit/model/indexing/rvalue_test.cpp
- src/test/unit/model/indexing/rvalue_varmat_test.cpp
- src/test/unit/model/indexing/util.hpp
There were some include order issues with https://github.com/stan-dev/stanc3/pull/898 that this PR fixes. This tries to cleanup some of the init orders so that we only bring in what we need for the rvalue and assign functions. Mostly that involves not including `/prim/fun.hpp` and `/rev/fun.hpp`. The only extra functions we need from those are really `to_ref()` and `adjoint_of()`
Cleanup include orders so new var matrix compiles.
No new tests, I pulled down a few of the failing stan models locally and checked they compiled. 
By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following …
> fixup indexing include orders

- src/stan/callbacks/unique_stream_writer.hpp
- src/test/unit/callbacks/unique_stream_writer_test.cpp
Small fix for https://github.com/stan-dev/cmdstan/pull/987, @wds15 we just need to set the precision of the local stringstreams in `unique_stream_writer` so that formatting stays correct.
Bug fix
Tests for preserving precision can be run with 
```
./runTests.py ./src/test/unit/callbacks/unique_stream_writer_test.cpp
```
Nope!
> local stringstreams preserve precision of main stream in unique_stream_writer

- src/stan/io/array_var_context.hpp
- src/stan/io/chained_var_context.hpp
- src/stan/io/dump.hpp
- src/stan/io/empty_var_context.hpp
- src/stan/io/random_var_context.hpp
- src/stan/io/var_context.hpp
- src/test/unit/io/array_var_context_test.cpp
Allow for intake of complex numbers in Stan. This PR mainly adds a new function called vals_c which allow for intake of complex numbers in a Stan program.
All documentation for complex numbers is available at https://github.com/stan-dev/docs/pull/378. 
Testing is available in src/test/unit/io/array_var_context_test.cpp
None
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Nicholas DiDio
> [WIP] Complex numbers vals_c

- src/stan/model/rethrow_located.hpp
Marks `rethrow_located` as never returning using the [noreturn attribute](https://en.cppreference.com/w/cpp/language/attributes/noreturn). This should allow us to simplify the existing code generation in stanc3, as currently we generate this code:
```c++
try {
....
} catch (const std::exception& e) {
stan::lang::rethrow_located(e, locations_array__[current_statement__]);
// Next line prevents compiler griping about no return
throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
}
```
This should make that extra `throw` unnecessary. 
Let the compiler know that rethrow_located will never return
I've tested this in a local cmdstan instance, though I was not able to get the error described in the comment to appear, with or without this change.
None
None
Please list the …
> Mark rethrow_located as [[noreturn]]

- src/stan/io/reader.hpp
- src/stan/model/indexing/rvalue.hpp
Hi @hsbadr this PR is a companion to the Math PR, and adds changes needed for the rstan revdeps to build with the rstan 2.21 & StanHeaders 2.26 combo.
The `rvalue` changes are needed because they were returning `Eigen::Block` types, which caused build errors for `idem` and `ubms`.
The `reader` changes were needed to allow for the vectorised `offset_constrain`, to fix build errors with `ppcseq`
> StanHeaders patches for RStan 2.21

- src/stan/model/indexing/rvalue.hpp
Hey @hsbadr, got another rvalue return that needed to be a plain type for a reverse dependency (`idem`) to build.
Andrew
> Additional eval return

- Jenkinsfile
2nd step of https://github.com/stan-dev/stan/issues/3075 
Simply switches integration tests to use stanc3 test/integration/good models
See issue for more.
Rok Češnovar
> Switch to stanc3 test models for integration tests

- src/test/unit/variational/advi_univar_no_constraint_test.cpp
- src/test/unit/variational/advi_univar_with_constraint_test.cpp
Adds namespace qualifiers in a couple of spots. After https://github.com/stan-dev/math/pull/2612, Stan Math will have overloads for all primitive scalar argument types and we need to avoid ambiguity in a couple of places.
Rok Češnovar
> add std:: in tests to avoid ambiguity

- src/stan/callbacks/stream_writer.hpp
- src/stan/callbacks/unique_stream_writer.hpp
This is a simpler fix for https://github.com/stan-dev/cmdstan/issues/1055 where we just do a check if the `output_` unique pointer is a `nullptr` and if so we don't write anything. For the diagnostics fix we just need to change line 502 in command.hpp so that if the diagnostic file to be written to is the default `""` then we just insert a nullptr i.e.
```cpp
if (diagnostic_file != "") {
auto diagnostic_filename
= diagnostic_name + name_iterator(i) + diagnostic_ending;
diagnostic_writers.emplace_back(
std::make_unique<std::fstream>(diagnostic_filename,
std::fstream::out),
"# ");
} else {
diagnostic_writers.emplace_back(nullptr, "# ");
}
```
Doing this and comparing 2.28 and 2.27 things look fine to me (in fact a bit faster but just a little so could be fuzz)
```
Elapsed Time: 7.075 …
```
> Do not write to stream when given a nullptr in the writer

- Jenkinsfile
Integration tests sometimes fail because of precompiled header issues. I think there is something leftover from previous runs that causes issues. Adding a clean-all step should help.
Rok Češnovar
> Add clean-all to integration tests

- Jenkinsfile
Integration tests still occasionally fail with the `.pch` error. Still haven't gotten to the bottom of why. It seems that somewhere in CI we are not cleaning up after the last run. This is a CI-only issue so I am going to try running without integration tests to see what the test runtime hit is. If its not bad, lets just do that to avoid this annoyance.
Rok Češnovar
> Disable precompiled headers for integration tests

- src/stan/io/serializer.hpp
- src/stan/model/indexing/access_helpers.hpp
- src/stan/model/indexing/assign.hpp
- src/stan/model/indexing/assign_varmat.hpp
- src/stan/model/indexing/rvalue.hpp
- src/stan/model/indexing/rvalue_index_size.hpp
- src/test/unit/model/indexing/assign_test.cpp
- src/test/unit/model/indexing/assign_varmat_test.cpp
- src/test/unit/model/indexing/rvalue_test.cpp
- src/test/unit/model/indexing/rvalue_varmat_test.cpp
This Fixes #3076 so that negative length min_max and max indices return a slice of size 0 instead of returning a reversing index. This also Fixes #3084 so that matrices can only be assigned matrices of the same size (unless the assigning matrix has 0 rows and 0 columns which means it is uninitialized and okay to override.
Provide backwards compatibility for negative indexing
Tests have been added to `src/test/unit/model/indexing/rvalue_test.cpp` and `src/test/unit/model/indexing/assign_test.cpp` to check that negative sized max and min_max indices return objects of the correct size.
I followed from @bob-carpenter 's answers from https://github.com/stan-dev/stan/issues/3076#issuecomment-954265563. The main thing that needs to be checked for a review is that 
We should probably update the …
> Fix assign and lvalue to return 0 row/col/size objects for negative indexing

- Jenkinsfile
This PR will handle Jenkins CI migration to Flatiron Institute. Currently, WIP until we iron out errors, plugins, and other requirements.
We will run mc-stan and flatiron Jenkins in parallel until it's stable and most of the main jobs are workings, after that, we will decommission mc-stan and migrate entirely to Flatiron Institute.
There may be side effects where two jobs would try to do the same objective like updating a submodule, will try to avoid this as much as possible.
Please list the copyright holder for the work you are submitting (this will be you or your assignees, such as a university or company): Toptal …
> [WIP] Move ci to flatiron institute

- src/stan/io/dump.hpp
The `stan` source included in `StanHeaders` 2.26 does not have an `#include` statement for the `validate_dims` header, causing compile errors in some instances. This PR adds the necessary `USE_STANC3` conditional include 
> Add validate_dims include

- src/stan/mcmc/hmc/base_hmc.hpp
Add `const noexcept` modifiers to the three accessors related to step-size (nominal, current, and jitter).
Allow retrieving those values from a `const` object.
Trivial.
None.
N/A.
Tal Kedar
> [base_hmc] add 'const noexcept' to stepsize accessors

- .github/workflows/testing.yml
- src/stan/model/model_base.hpp
- src/stan/model/model_base_crtp.hpp
- src/test/unit/model/model_base_test.cpp
The model base class exposes overloads to all the log_prob functions for `double` and `math::var`. It would be useful to expose `math::fvar<var>` overloads to allow higher-order autodiff from base class instances, but this does not work with all Stan models (particularly ODE models and other uses of implicit functions).
This PR introduces opt-in only overloads. This allows downstream users, who want to provide model Hessians or Hessian-vector products, to still use `stan::model::model_base` as a type. Currently, the Hessian functionality in (e.g.) `stan::model::hessian` relies on a template type which can never be filled by `stan::model::model_base`; after this PR it would be possible if the define `STAN_MODEL_AD_HESSIAN` is used.
These signatures are identical to the previously existing …
> Add a #define flag to enable nested autodiff in model_base class

- Jenkinsfile
The step "Integration Linux" is identical to two steps in stanc3's CI ("Compile tests - good" and "Compile tests - example models") but takes ~3 hours while those two combined take 65 minutes. So far as @serban-nicusor-toptal and I can tell, the only difference between the two setups is PRECOMPILED_HEADERS and the misspecified PARALLEL setting.
> Improve CI times

- .github/workflows/testing.yml
Pinned GH Actions to use ubuntu-20.04 instead of ubuntu-latest which now points to ubuntu-22.04.
For more information please see: https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/
Fix following error: https://github.com/stan-dev/stan/actions/runs/3707225050/jobs/6283381831
Pipeline should pass
None
None
> Pinned GH Actions to use ubuntu-20.04

- Jenkinsfile
Fix failure due to `./runTests.py: /usr/bin/python: bad interpreter: No such file or directory`
> Use 'python3' on Mac Integration testing

- src/stan/services/util/create_rng.hpp
This makes it so at least 1 entry is discarded from new RNG instances, even when `chain == 0`
Closes #3167 
See https://godbolt.org/z/G953v67c4 and the model/code provided in #3167
RNG seeds from previous versions of Stan will have different behavior for chain_id 0 and in the transformed data block. Users who did not use `_rng` functions in transformed data or manually set their chain id to 0 will not observe different behavior.
None
- …
> Always discard at least 1 entry in new RNGs

- src/stan/io/json/json_data.hpp
- src/test/unit/io/json/json_data_test.cpp
Follow on to #3165, this allows for any variable name to be "validated" if the expected size is `0`. 
This is necessary because 
` { "foo" : [] }`
is a valid JSON for `array[0] tuple(real, real) foo`, but the Stan compiler will request information on `"foo.1"` and `"foo.2"` which don't exist.
Tests were added
If an object has a 0 dimension (e.g. is size 0), then it is technically no longer required to be in the JSON at all. E.g., for `matrix[0, 3] bar`, valid JSONs are now ` { "bar" : [] }`, `{ "bar" : [[]] }`, **and** simply `{ }`
By submitting this pull request, the copyright holder is agreeing to license the submitted work under the …
> Relax requirements for 0-sized data objects in JSON

- src/stan/services/util/gq_writer.hpp
- src/test/test-models/good/services/test_gq.stan
- src/test/unit/services/util/gq_writer_test.cpp
Closes https://github.com/stan-dev/cmdstan/issues/1007. Since https://github.com/stan-dev/stanc3/pull/1165 we have made sure that `write_array` always populates the array with NaNs, so writing it out is safe even after an exception. 
Standalone generate quantities behavior now matches that of sampling (nans output if write_array fails) and the number of rows in the output of standalone generated quantities is now always the number of rows in the input `fitted_params`.
The example from https://github.com/stan-dev/cmdstan/issues/1007 works well
By submitting this pull request, the copyright holder is agreeing to license the submitted work …
> Standalone GQ: Output NaNs when exception is caught

- src/stan/io/random_var_context.hpp
- src/test/unit/io/random_var_context_test.cpp
This uses the new arguments from https://github.com/stan-dev/stan/pull/3139 to avoid doing some extra work in `random_var_context`.
The same behavior as before, with less code.
> Clean up dimension and name logic in random_var_context

- src/stan/io/deserializer.hpp
This makes the minimal necessary changes to allow the `deserializer` class to accept const references. 
Allow the passing of `const std::vector<T>&` to `deserializer`
None
> Make deserializer's map members const

- src/stan/services/optimize/laplace_sample.hpp
- src/test/unit/services/optimize/laplace_jacobian_test.cpp
- src/test/unit/services/optimize/laplace_sample_test.cpp
Closes #3183. This changes the names of the `log_p` and `log_q` output columns to `log_p__` and `log_q__`, and moves them to the start to match up with other algorithms.
Unfortunately this was not caught before release, but because cmdstanpy and cmdstanr don't have support for this built-out yet I think we can say that it is a bug fix rather than a breaking change, and release it in 2.32.1 next week (see https://github.com/stan-dev/cmdstan/issues/1154)
I believe the CmdStan implementation also assumes this ordering in its tests, so those may briefly break if we merge this.
The docs page (https://mc-stan.org/docs/cmdstan-guide/laplace-sampling.html) will need to be updated
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a …
> Laplace sampling: change output columns for consistency

- src/stan/services/pathfinder/multi.hpp
Fixes CSV names for multi pathfinder so that the lp names are first 
> update colnames for pathfinder multi so that lps are first

- src/doxygen/doxygen-footer.html
- src/doxygen/doxygen.cfg
- src/stan/io/json/json_data.hpp
- src/stan/io/json/json_data_handler.hpp
- src/stan/mcmc/hmc/nuts/base_nuts.hpp
- src/stan/mcmc/hmc/xhmc/base_xhmc.hpp
- src/stan/model/indexing/assign_cl.hpp
- src/stan/model/indexing/rvalue.hpp
- src/stan/model/prob_grad.hpp
- src/stan/services/pathfinder/psis.hpp
- src/stan/services/pathfinder/single.hpp
Closes #3208 and fixes a variety of other typos, mostly in comments. 
I found the other typos using [codespell](https://github.com/codespell-project/codespell), which honestly seems like it is a decent candidate for inclusion in a CI pipeline somewhere.
> Fix various spelling mistakes

- src/stan/callbacks/structured_writer.hpp
- src/stan/services/experimental/advi/fullrank.hpp
- src/stan/services/experimental/advi/meanfield.hpp
- src/stan/services/optimize/bfgs.hpp
- src/stan/services/optimize/laplace_sample.hpp
- src/stan/services/optimize/lbfgs.hpp
- src/stan/services/optimize/newton.hpp
- src/stan/services/pathfinder/multi.hpp
- src/stan/services/pathfinder/single.hpp
- src/stan/services/sample/fixed_param.hpp
- src/stan/services/sample/hmc_nuts_dense_e.hpp
- src/stan/services/sample/hmc_nuts_dense_e_adapt.hpp
- src/stan/services/sample/hmc_nuts_diag_e.hpp
- src/stan/services/sample/hmc_nuts_diag_e_adapt.hpp
- src/stan/services/sample/hmc_nuts_unit_e.hpp
- src/stan/services/sample/hmc_nuts_unit_e_adapt.hpp
- src/stan/services/sample/hmc_static_dense_e.hpp
- src/stan/services/sample/hmc_static_dense_e_adapt.hpp
- src/stan/services/sample/hmc_static_diag_e.hpp
- src/stan/services/sample/hmc_static_diag_e_adapt.hpp
- src/stan/services/sample/hmc_static_unit_e.hpp
- src/stan/services/sample/hmc_static_unit_e_adapt.hpp
- src/stan/services/util/initialize.hpp
- src/stan/services/util/run_adaptive_sampler.hpp
- src/test/unit/services/optimize/laplace_sample_test.cpp
- src/test/unit/services/sample/hmc_nuts_dense_e_adapt_parallel_match_test.cpp
- src/test/unit/services/sample/hmc_nuts_diag_e_adapt_parallel_match_test.cpp
- src/test/unit/services/util/initialize_test.cpp
Currently, the services functions are inconsistent on whether or not they will throw an exception. The versions which accept `num_chains` should never throw, but the older ones will throw if initialization fails.
This consistently puts `utils::initialize` in a `try` block. 
Additionally, we are currently using `logger.info` for messages which are errors, and in several places not logging an error where we could (e.g., the `catch` blocks accompanying the above `try`s).
Improved error logging and exception safety in the services functions
By submitting this pull request, the copyright holder is agreeing to license the submitted work under …
> Service functions: Consistent exception handling and error logging

- Jenkinsfile
Fix a typo in the quality gate filter, this fails downstream tests in Math by being unstable, see [pipeline](https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FMath/detail/PR-2822/85/pipeline/).
> Fix typo in quality gate filter

- src/stan/model/indexing/rvalue_cl.hpp
For https://github.com/stan-dev/math/pull/2905 I need to make a hard copy of the event vector for OpenCL before making a copy to go from a tbb concurrent vector to a standard vector.
In the downstream PR above the stan tests should now pass
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Simons Foundation
> adds wrapper to hard copy write events for opencl copies

- src/stan/model/indexing/assign.hpp
- src/test/unit/model/indexing/assign_test.cpp
Fixes #3150 to do a size check when assigning to the inner elements of an array whose inner elements also have dimensions.
Stop the use of accidental ragged arrays
New test added that can be run with 
```c++
python ./runTests.py -j18 ./src/test/unit/model/indexing/assign_test.cpp
```
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Simons Foundation
> Adds size checking to uni index array assignment

- src/stan/services/pathfinder/psis.hpp
Fixes #3223. Improves misleading Pareto k warning message. I didn't see any tests that check the text of this message so I didn't edit any tests.
The old message said "...which often indicates model misspecification", but this is somewhat misleading. More accurate is 
"... which may indicate a poor approximation of the target distribution or model misspecification". 
@avehtari What do you think of this message? 
Change text of warning message. 
I suppose run a model that results in the warning message (are there any we know to definitely trigger the warning? Aki will probably know), but I think it’s sufficient to just look at the edited text. 
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia …
> improve Pareto k warning message

- src/stan/callbacks/json_writer.hpp
- src/stan/callbacks/structured_writer.hpp
- src/test/unit/callbacks/json_writer_test.cpp
Follow up on #3191.
This PR:
- Improves the output of the JSON writer to be a bit more human readable (mainly by more consistently outputting newlines between key:value pairs)
- Updates both `structured_writer` and `json_writer` such that the latter can be a subclass of the former. 
- Fixed a bug where `j.begin_record("foo"); j.end_record(); j.write("anything here");` would generate invalid JSON …
> Make json_writer a structured_writer, improve output formatting

- src/stan/callbacks/json_writer.hpp
- src/stan/callbacks/structured_writer.hpp
- src/stan/model/model_base_crtp.hpp
- src/stan/optimization/bfgs_linesearch.hpp
- src/stan/services/sample/hmc_nuts_unit_e_adapt.hpp
Resolves warnings, see quality gate: https://jenkins.flatironinstitute.org/job/Stan/job/Stan/job/develop/162/pipeline_gcc4/
> Resolve various warnings due to doxygen, keywords

- src/test/unit/callbacks/json_writer_test.cpp
- src/test/unit/services/pathfinder/normal_glm_test.cpp
Follow up on #3230, uses the new utility function in a couple places we were directly using RapidJSON for testing
> Use stan::test::is_valid_JSON consistently

- src/test/unit/model/indexing/assign_cl_test.cpp
Fixes a bug in the stan opencl assign tests that reuses a `var_value<matrix_cl<double>>` after `stan::math::recover_memory()` is called. This popped up in https://github.com/stan-dev/math/pull/2905 in the math. My guess is that this could be the cause of why sometimes these tests would fail randomly.
@t4c1 if you have any time could you take a look at this? I wasn't sure if this was intended as some part of the test or not and I'm missing something. You can replicate the error this fixes with the following
```bash
git clone --recursive git@github.com:stan-dev/stan.git
cd lib/stan_math
git checkout feature/threadsafe-matrixcl
cd ../../
python ./runTests.py ./src/test/unit/model/indexing/assign_cl_test.cpp
```
It's odd because after `recover_memory()` is called `m_empty_v_cl` will have a …
> update opencl assign test to reassign zero sized vector after recover_memory() 

- src/stan/services/pathfinder/multi.hpp
Since  https://github.com/stan-dev/math/pull/2955, building cmdstan has been issuing the following warning:
```
stan/lib/stan_math/lib/boost_1.81.0/boost/config/pragma_message.hpp:24:34: note: ‘#pragma message: This header is deprecated. Use <iterator> instead.’
24 | # define BOOST_PRAGMA_MESSAGE(x) _Pragma(BOOST_STRINGIZE(message(x)))
|                                  ^~~~~~~
stan/lib/stan_math/lib/boost_1.81.0/boost/config/pragma_message.hpp:24:34: note: in definition of macro ‘BOOST_PRAGMA_MESSAGE’
24 | # define BOOST_PRAGMA_MESSAGE(x) _Pragma(BOOST_STRINGIZE(message(x)))
|                                  ^~~~~~~
stan/lib/stan_math/lib/boost_1.81.0/boost/iterator.hpp:10:1: note: in expansion of macro ‘BOOST_HEADER_DEPRECATED’
10 | BOOST_HEADER_DEPRECATED("<iterator>")
| …
```
> Remove unused deprecated boost header include

- Jenkinsfile
Add jenkins configuration to remove old build logs and artifacts after some time to avoid running out of disk space. Feel free to tweak the specific numbers, as long as we don't keep them forever.
> jenkins: cleanup old build logs

- src/stan/services/optimize/bfgs.hpp
- src/stan/services/optimize/lbfgs.hpp
Similar to #3214, this makes it so an error message emitted by bfgs or lbfgs is not split between stderr and stdout but is entirely sent to stderr.
> Log optimization errors on error channel

- src/stan/services/pathfinder/multi.hpp
The current design is such that the order of the single-pathfinder draws is determined by the order their thread completes, so a random seed does not always produce the same output of multi-pathfinder. 
More details are given in #3237
Closes #3237 
> Fix nondeterminism in multi-Pathfinder

- Jenkinsfile
Due to some Jenkins changes, we have to migrate away from the old way of killing concurrent builds.
> Replace usage of killOldBuilds with disableConcurrentBuilds

- src/stan/analyze/mcmc/compute_potential_scale_reduction.hpp
`stan::analyze::compute_potential_scale_reduction` still attempts to calculate the PSR if there are 0 draws passed, which is currently causing a segfault when calling `stansummary` on the output from `optimize`:
```
andrew@Andrews-MacBook-Air bernoulli % ./bernoulli optimize data file=bernoulli.data.json
...
andrew@Andrews-MacBook-Air bernoulli % ../../bin/stansummary output.csv
Warning: non-fatal error reading adaptation data
Assertion failed: (index >= 0 && index < size()), function operator(), file DenseCoeffsBase.h, line 181.
zsh: abort      ../../bin/stansummary output.csv
```
No segfault
Call `stansummary` with this applied.
N/A
N/A
By …
> PSR: Return early if no draws

- src/stan/callbacks/unique_stream_writer.hpp
- src/stan/callbacks/writer.hpp
- src/stan/services/pathfinder/multi.hpp
- src/stan/services/pathfinder/single.hpp
- src/test/unit/services/pathfinder/normal_glm_test.cpp
- src/test/unit/services/pathfinder/util.hpp
Adds the request from @avehtari in #3242 to add an option for turning off resampling and calculating the lp.
If `psis_resample` is false then psis resampling is not performed and the full set of samples is returned from all the individual pathfinders. 
If `return_lp` is false then the lp values are not calculated for each sample. I think a lot of upstream packages assume that a `lp__` column at least exists so here I just set the column of lp values to `NaN`. This also means psis resampling is turned off since we cannot calculate the lp ratio and the full set of samples is returned from all the individual pathfinders. 
Something questionable here is that since we have to calculate the lp values for the set of samples we compute the elbo metric on we just get those lp calculations for …
> Adds option to turn off psis resampling and lp calculation for pathfinder

- src/stan/io/json/json_data_handler.hpp
Depending on the user's locale, using `std::regex` with the MinGW GCC in RTools will result in a memory leak and the program hangs.
This has previously been reported as bug to MinGW [here](https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/CABFfbXvurKZjO8tjrFrirwy_Spego-nRvOksjkmnDtYsESu%3DYQ%40mail.gmail.com/#msg37203838), but it is still an issue.
For Stan, this can cause a hang when parsing JSON data (seen recently as the cause of this [downstream issue](https://github.com/andrjohns/StanEstimators/issues/1)). We can instead use the Boost Regex headers as a drop-in replacement, which I've verified resolve the issue.
Avoid hanging under certain locales
N/A
N/A
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a …
> [BUGFIX] Replace STL regex with Boost for MinGW bug

- src/stan/io/json/json_handler.hpp
With GCC 13, some C++ Standard Library headers have been changed to no longer include other headers that were being used internally by the library (see, e.g. [this](https://gcc.gnu.org/gcc-13/porting_to.html)). This has affected [many other projects](https://duckduckgo.com/?q=gcc13+cstdint+site%3Agithub.com&t=ffab). 
I noticed this when trying to run the tests with:
`python runTests.py -j$(nproc) src/test`
The fix is simple, `<cstdint>` has to be included manually.
Fix build with g++13
Run the tests
None? …
> Fix build with gcc13

- Jenkinsfile
We had an || instead of an && so this was always `true`, which led to problems when multiple Math PRs were running at once. 
Cmdstan has the same issue currently, I'll open a separate PR
> Properly allow multiple downstream jenkins runs

- src/stan/services/optimize/laplace_sample.hpp
- src/test/unit/services/optimize/laplace_sample_test.cpp
Closes #3215 
Closes #3260 
This adds two new options to the laplace approximation service function. The first is a boolean `calculate_lp`, similar to #3249 
The second is a structured writer which will save the result of the evaluation at the mode, namely it will produce a JSON file like
```
{
"lp_mode" : 0,
"gradient" : [ 0, 0 ],
"Hessian" : [ [ -2.77778, 2.22222 ], [ 2.22222, -2.77778 ] ]
}
```
Tests added
I left the existing function for backwards compatibility. The above arguments default to `true` and a no-op writer, respectively.
Added inline documentation, online doc will come with the cmdstan PR.
By submitting this pull request, …
> Add option to output Hessian, disable LP calculations in Laplace

- src/stan/mcmc/hmc/hamiltonians/base_hamiltonian.hpp
- src/stan/optimization/bfgs.hpp
- src/stan/optimization/newton.hpp
- src/stan/services/experimental/advi/fullrank.hpp
- src/stan/services/experimental/advi/meanfield.hpp
- src/stan/services/optimize/bfgs.hpp
- src/stan/services/optimize/lbfgs.hpp
- src/stan/services/optimize/newton.hpp
- src/stan/services/pathfinder/multi.hpp
- src/stan/services/pathfinder/single.hpp
- src/stan/services/sample/fixed_param.hpp
- src/stan/services/sample/hmc_nuts_dense_e.hpp
- src/stan/services/sample/hmc_nuts_dense_e_adapt.hpp
- src/stan/services/sample/hmc_nuts_diag_e.hpp
- src/stan/services/sample/hmc_nuts_diag_e_adapt.hpp
- src/stan/services/sample/hmc_nuts_unit_e.hpp
- src/stan/services/sample/hmc_nuts_unit_e_adapt.hpp
- src/stan/services/sample/hmc_static_dense_e.hpp
- src/stan/services/sample/hmc_static_dense_e_adapt.hpp
- src/stan/services/sample/hmc_static_diag_e.hpp
- src/stan/services/sample/hmc_static_diag_e_adapt.hpp
- src/stan/services/sample/hmc_static_unit_e.hpp
- src/stan/services/sample/hmc_static_unit_e_adapt.hpp
- src/stan/services/sample/standalone_gqs.hpp
- src/stan/services/util/gq_writer.hpp
- src/stan/services/util/mcmc_writer.hpp
Closes #3258. This changes any place which caught `std::exception` from the model to only catch `std::domain_error`, matching what is done during initialization. 
This prevents odd behavior like an indexing exception that only occurs randomly being swallowed if initialization happens to pass, and allows things like an `exit()` function in the language.
Cause certain exceptions to terminate the inference algorithms.
This model will usually initialize but quickly fail now: 
```stan
parameters {
real mu;
}
model {
mu ~ normal(0, 1);
if (mu > 1) {
array[1] int sigma;
print(sigma[2]);
}
}
```
I've installed handlers in the service functions, but code that calls the internals of these algorithms (e.g `run_adaptive_sampler`) _not_ through the services will need to be ready to catch exceptions …
> Only swallow domain_errors in various algorithms 

- src/stan/services/util/create_rng.hpp
- src/test/unit/mcmc/hmc/nuts/base_nuts_test.cpp
- src/test/unit/mcmc/hmc/nuts/softabs_nuts_test.cpp
- src/test/unit/mcmc/hmc/nuts/unit_e_nuts_test.cpp
- src/test/unit/mcmc/hmc/static_uniform/derived_static_uniform_test.cpp
- src/test/unit/mcmc/hmc/xhmc/base_xhmc_test.cpp
- src/test/unit/mcmc/hmc/xhmc/softabs_xhmc_test.cpp
- src/test/unit/mcmc/hmc/xhmc/unit_e_xhmc_test.cpp
- src/test/unit/services/pathfinder/normal_glm_test.cpp
- src/test/unit/services/pathfinder/util.hpp
- src/test/unit/variational/advi_messages_test.cpp
- src/test/unit/variational/eta_adapt_small_test.cpp
Closes #3256. This switches the pRNG used by default in the services and tests to be `boost::mixmax`, as recommended by the boost maintainers: https://github.com/boostorg/random/issues/92 
Resolve both https://github.com/stan-dev/stan/issues/3167 and https://github.com/stan-dev/cmdstan/issues/1241, avoid other issues with RNG quality.
Seeds used in previous versions will have different meanings from this version on. **We should note this in the release notes**.
Additionally, by changing the type alias of `rng_t` introduced in #3263, this PR changes the ABI of the model base, so code which calls it directly will need to be aware. This is most obviously relevant for things which use the standalone-functions feature of stanc like cmdstanr and rstan, I believe. @andrjohns 
Please list the …
> Change default RNG to boost::mixmax 

- src/stan/services/pathfinder/psis.hpp
- src/stan/services/pathfinder/single.hpp
Closes #3268. Now when the number of draws requested is smaller than the number of draws the ELBO calculations do internally, they are truncated to the expected size rather than all returned. 
I also fixed up #3278 
I have a test [in another project](https://github.com/WardBrian/tinystan/blob/4a758bd221d81a0e9627f0624070eb9597c3dec3/clients/python/tests/test_pathfinder.py#L81-L91), I wasn't sure if we wanted to adapt one for here or not. 
- …
> Pathfinder: stop returning more draws than requested

- src/stan/services/util/create_rng.hpp
- src/test/unit/mcmc/hmc/nuts/base_nuts_test.cpp
- src/test/unit/mcmc/hmc/nuts/softabs_nuts_test.cpp
- src/test/unit/mcmc/hmc/nuts/unit_e_nuts_test.cpp
- src/test/unit/mcmc/hmc/static_uniform/derived_static_uniform_test.cpp
- src/test/unit/mcmc/hmc/xhmc/base_xhmc_test.cpp
- src/test/unit/mcmc/hmc/xhmc/softabs_xhmc_test.cpp
- src/test/unit/mcmc/hmc/xhmc/unit_e_xhmc_test.cpp
Prevents the poor behavior seen in #3285.
The boost::mixmax rng is actually initialized with 128 bits of state. The overload we were previously calling was synonymous with `rng(0,0, 0, seed+chain)`. This PR changes to `rng(0,1,seed,chain)`. In addition to ensuring that the full 128 bits are never all zero, it also makes adjacent seeds more independent; previously seed=1 chain=1, seed=2 chain=0, and seed=0 chain=2 would all yield the same seeding.
I am still awaiting on confirmation from the boost devs that this configuration of the RNG preserves the desirable property that `chain` and `chain+1` yield independent streams, hence the draft status.
Closes #3285 
See the [updated godbolt](https://godbolt.org/z/KPPad8P7j) which shows that the single `1` prevents the deterministic behavior
Seeds …
> Ensure mixmax rng is not initialized with all zeros
