stan-dev/stan

src/test/performance/logistic_test.cpp
src/test/performance/plot_performance.R
src/test/performance/utility.hpp

Cleaned up performance test. Added documentation.
Added documentation for the performance test.
Replaced `Eigen::Matrix` with `std::vector`.
Hopefully this will be clearer to the next person that sees the test.
Look at `src/test/performance/logistic_test.cpp`.
Run: `> ./runTests.py src/test/performance/logistic_test.cpp`
None.
Updated documentation in code.
@bob-carpenter

Update performance test

---

makefile

Fixes #1277. Add out-of-tree make/local.

---

src/test/performance/plot_performance.R

fixes #1279. moves the label within view

---

RELEASE-NOTES.txt

Updates release notes.
Includes release notes for v2.6.1.
See RELEASE_NOTES.txt
None.
Included.
No one.

updating release notes

---

src/stan/math/prim/scal/meta/get.hpp

add another #include

---

src/test/unit/math/fwd/mat/prob/lkj_corr_test.cpp
src/test/unit/math/fwd/mat/prob/matrix_normal_test.cpp
src/test/unit/math/mix/mat/prob/lkj_corr_test.cpp
src/test/unit/math/mix/mat/prob/matrix_normal_test.cpp

Fixes case insensitive includes.
Fixes broken tests.
You'll have to look if you're on Mac or Windows. Linux can verify by running the changed tests.
None.
None.
Anyone.

Fixes capitalization issue with include eigen numtraits

---

RELEASE-NOTES.txt

[skip ci]
Adding release notes for v2.6.2.
None.
None.

added release notes for v2.6.2

---

src/docs/stan-reference/title.tex

Fixes Michael Betancourt's affiliation.

[skip ci] fixing Mike's affiliation

---

src/test/unit/math/fwd/scal/meta/traits_test.cpp
src/test/unit/math/mix/scal/meta/traits_test.cpp
src/test/unit/math/prim/arr/meta/is_vector_like_test.cpp
src/test/unit/math/prim/mat/meta/is_vector_like_test.cpp
src/test/unit/math/prim/scal/meta/is_vector_like_test.cpp
src/test/unit/math/prim/scal/meta/traits_test.cpp
src/test/unit/math/rev/scal/meta/traits_test.cpp

Add tests for `is_vector_like`.
Verify `is_vector_like` behaves properly.
See the additional test code.
None. No code has changed.
None. Documentation should already be in place.
Bob?

added tests for is_vector_like

---

RELEASE-NOTES.txt

Added release notes for v2.6.3.
None.
None.

adding release notes for 2.6.3

---

src/test/unit/optimization/lbfgs_update_test.cpp

Allows the tests to be compiled using g++ 4.4.
Compile tests.
None. Change to test only. Should compile with newer version of g++ or clang++ without any problems.
None.
Anyone.

1514: fixed template issue

---

.travis.yml

This accommodates a travis-ci update.
Updates the .travis.yml script to use the container based infrastructure.
N/A.
Tests on travis should finish sooner.
N/A
N/A

migrating travis script for container based infrastructure

---

src/python/runTests.py

Removes unused python script.
Remove script.
Just look at diff.
None. This isn't used anywhere.
None.
@bob-carpenter

removing unused python script

---

make/tests

Fixes #1618. Issues with makefile.
Make the Stan makefile a little better.
Everything should work the same way.
Make should run a little quicker, I hope.
None required.
No one.

Updating makefile... hopefully this fixes the issues we're having

---

README.md

Title.
Part of a round of pull requests, splitting out #1590. See #1590 for the blueprint.
None
N/A
None
N/A
N/A

Add approximate Bayesian inference to README.md

---

src/stan/services/arguments/arg_variational_eta.hpp

Fixes argument bug introduced with #1638.

Fixes variational eta argument

---

src/docs/stan-reference/programming.tex

Add subindex for inverse transform to reverse stadardization of y.

Docs standardized variable notation

---

src/stan/mcmc/hmc/base_hmc.hpp
src/stan/mcmc/hmc/hamiltonians/base_hamiltonian.hpp
src/stan/mcmc/hmc/hamiltonians/dense_e_metric.hpp
src/stan/mcmc/hmc/hamiltonians/diag_e_metric.hpp
src/stan/mcmc/hmc/hamiltonians/unit_e_metric.hpp
src/stan/mcmc/hmc/integrators/base_integrator.hpp
src/stan/mcmc/hmc/integrators/base_leapfrog.hpp
src/stan/mcmc/hmc/integrators/expl_leapfrog.hpp
src/stan/mcmc/hmc/nuts/adapt_dense_e_nuts.hpp
src/stan/mcmc/hmc/nuts/adapt_diag_e_nuts.hpp
src/stan/mcmc/hmc/nuts/adapt_unit_e_nuts.hpp
src/stan/mcmc/hmc/nuts/base_nuts.hpp
src/stan/mcmc/hmc/nuts/dense_e_nuts.hpp
src/stan/mcmc/hmc/nuts/diag_e_nuts.hpp
src/stan/mcmc/hmc/nuts/unit_e_nuts.hpp
src/stan/mcmc/hmc/static/adapt_dense_e_static_hmc.hpp
src/stan/mcmc/hmc/static/adapt_diag_e_static_hmc.hpp
src/stan/mcmc/hmc/static/adapt_unit_e_static_hmc.hpp
src/stan/mcmc/hmc/static/base_static_hmc.hpp
src/stan/mcmc/hmc/static/dense_e_static_hmc.hpp
src/stan/mcmc/hmc/static/diag_e_static_hmc.hpp
src/stan/mcmc/hmc/static/unit_e_static_hmc.hpp
src/test/unit/mcmc/hmc/base_hmc_test.cpp
src/test/unit/mcmc/hmc/base_nuts_test.cpp
src/test/unit/mcmc/hmc/base_static_hmc_test.cpp
src/test/unit/mcmc/hmc/integrators/expl_leapfrog2_test.cpp
src/test/unit/mcmc/hmc/integrators/expl_leapfrog_test.cpp
src/test/unit/mcmc/hmc/mock_hmc.hpp

Removes template parameter from Hamiltonian.
Simplify code. Refactoring only. No change to behavior.
Run tests.
None.
If we need some more, please comment.
@betanalpha

Update hamiltonians to hold its point type

---

src/stan/services/arguments/argument.hpp
src/stan/services/arguments/argument_parser.hpp
src/stan/services/arguments/argument_probe.hpp
src/stan/services/arguments/categorical_argument.hpp
src/stan/services/arguments/list_argument.hpp
src/stan/services/arguments/singleton_argument.hpp
src/stan/services/arguments/unvalued_argument.hpp
src/stan/services/arguments/valued_argument.hpp
src/test/integration/services/arguments/argument_parser_test.cpp
src/test/integration/services/arguments/argument_test.cpp
src/test/integration/services/arguments/categorical_argument_test.cpp
src/test/integration/services/arguments/singleton_argument_test.cpp
src/test/integration/services/arguments/unvalued_argument_test.cpp
src/test/integration/services/arguments/valued_argument_test.cpp

Update the arguments to use the writer.
Use the writer for the arguments. This touches 14 files (roughly half are tests).
Run the tests.
This will affect the interfaces and I'll take care of it.
None added.
@betanalpha

Updating arguments to use base_writer

---

src/test/performance/logistic_test.cpp

Adding an additional test to make sure the output contains the adaptation info.
Adding another regression test.
Run the test. 
None. This adds another test.
None.
None.

Adding more output checks to 'freeze' behavior

---

src/docs/stan-reference/algorithms.tex

Updates the Stan manual to explain the new ADVI adaptation. 
See issue https://github.com/stan-dev/stan/issues/1704
Bring the manual up to date.
Read.
None.
@dustinvtran @syclik

modified manual to briefly explain eta adaptation warmup

---

.travis.yml

Add g++ testing on travis.
None.
None.

Test using g++ on travis

---

src/docs/stan-reference/acknowledgements.tex
src/docs/stan-reference/advanced.tex
src/docs/stan-reference/algorithms.tex
src/docs/stan-reference/distributions.tex
src/docs/stan-reference/functions.tex
src/docs/stan-reference/introduction.tex
src/docs/stan-reference/language.tex
src/docs/stan-reference/preface.tex
src/docs/stan-reference/process.tex
src/docs/stan-reference/programming.tex
src/docs/stan-reference/stan-manuals.sty
src/docs/stan-reference/stan-reference.tex
src/docs/stan-reference/title.tex

Updates to  manual based on issues since 2.8.0.
Get manual ready to go for 2.9.0 release.
Build it.  You could check against the issue's checkboxes.
None.
Yes.
Anyone.

manual fixes completing issue #1617

---

src/stan/mcmc/chains.hpp
src/stan/mcmc/hmc/hamiltonians/diag_e_metric.hpp
src/stan/mcmc/hmc/integrators/base_integrator.hpp
src/stan/mcmc/hmc/integrators/base_leapfrog.hpp
src/stan/mcmc/hmc/integrators/expl_leapfrog.hpp
src/stan/mcmc/hmc/nuts/adapt_dense_e_nuts.hpp
src/stan/mcmc/hmc/nuts/adapt_diag_e_nuts.hpp
src/stan/mcmc/hmc/nuts/adapt_unit_e_nuts.hpp
src/stan/mcmc/hmc/nuts/dense_e_nuts.hpp
src/stan/mcmc/hmc/nuts/diag_e_nuts.hpp
src/stan/mcmc/hmc/nuts/unit_e_nuts.hpp
src/stan/mcmc/hmc/static/adapt_dense_e_static_hmc.hpp
src/stan/mcmc/hmc/static/adapt_diag_e_static_hmc.hpp
src/stan/mcmc/hmc/static/adapt_unit_e_static_hmc.hpp
src/stan/mcmc/hmc/static/dense_e_static_hmc.hpp
src/stan/mcmc/hmc/static/diag_e_static_hmc.hpp
src/stan/mcmc/hmc/static/unit_e_static_hmc.hpp

Cleaned up inconsistently formatted code.
Makes the code base better.
Look at the diff.
There was an implementation mistake in base_leapfrog.hpp that is fixed.
N/A.
@betanalpha

Cleanup code for writer

---

RELEASE-NOTES.txt

Just release notes.
2.10 release notes for Stan.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  Columbia University

release notes for 2.10

---

src/docs/stan-reference/language.tex

fix some typos in stan reference manual
fix documentation typos
manual inspection
none
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): I guess me, Jacob Egner; I don't care about copyright/license stuff though.  Do whatever you want.

fix table typos in Multiple Indexing section

---

make/tests

The integration tests were broken before. We had thought that adding `-fsyntax-only` was sufficient for code to compile, but we found out that it didn't instantiate enough.
This pull request will now instantiate the Stan program with the correct template instantiations.
This currently passes on develop now, but should fail:
```
make src/test/test-models/good/validate_conditional_op_good.hpp-test
```
or
```
./runTests.py src/test/integration/compile_models_test.cpp 
```
With this pull request, it fails now. We'll need to make sure everything else passes.
Makes sure our Stan programs are compilable in C++.
Run this for one file:
```
make src/test/test-models/good/validate_conditional_op_good.hpp-test
```
or to run all files:
```
./runTests.py src/test/integration/compile_models_test.cpp …
```

Compile models are fixed. They will now try to instantiate models with the types we need.

---

src/docs/stan-reference/distributions.tex
src/stan/lang/function_signatures.h
src/test/test-models/good/function-signatures/distributions/rngs.stan

Adding `bernoulli_logit_rng` to stan. Resolves https://github.com/stan-dev/stan/issues/2084
Companion to math library:
PR: https://github.com/stan-dev/math/pull/404 
Issue: https://github.com/stan-dev/math/issues/258
Run the tests, read the manual.
Added an item in distributions.tex
This is my first PR on the stan repo, so would appreciate eyes on this, but it's pretty simple. …

add bernoulli_logit_rng to language, manual, and tests.

---

src/docs/stan-reference/programming.tex

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Roman Cheplyaka
(although this change isn't even copyrightable...)

Reference: fix a typo

---

.travis.yml

Turn off the Travis build for OSX with gcc to save a little bit of time.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Dual Space LLC
By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses: 

[WIP] Don't need to test OSX with gcc anymore.

---

src/stan/mcmc/windowed_adaptation.hpp
src/test/unit/mcmc/windowed_adaptation_test.cpp

Addresses #2064 with a more clear warning message.
Easier to understand warning message.
Check the diff.
None.
None.
Anyone.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  Columbia University

Tweak windowed adaptation warning to be more readable

---

src/docs/stan-reference/functions.tex

- [ X ] Declare copyright holder and open-source license: see below
Eyeball
None
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Joshua Pritikin

Fix typo in cumulative_sum definition

---

src/test/performance/logistic_test.cpp

Updates the test to capture existing behavior. Behavior changed with a recent pull request.
Fixes test to match behavior.
Run on a Mac:
```
./runTest.py src/test/performance/logistic_test.cpp
```
None.
None.
Anyone.
Stan Group

Updates performance test.

---

src/docs/stan-reference/acknowledgements.tex
src/docs/stan-reference/algorithms.tex
src/docs/stan-reference/appendices.tex
src/docs/stan-reference/distributions.tex
src/docs/stan-reference/examples.tex
src/docs/stan-reference/functions.tex
src/docs/stan-reference/language.tex
src/docs/stan-reference/process.tex
src/docs/stan-reference/programming.tex
src/docs/stan-reference/stan-reference.tex
src/docs/stan-reference/title.tex

Fix all manual issues in #2265 
Enable release of 2.16.

manual for 2.16, fixes #2265

---

src/docs/stan-reference/programming.tex

Fixed mistakes in code for K-1 simplex

---

.travis.yml

Travis just switched to Trusty, which is broken for us by default. This switches us back to precise. After finishing up the build refactoring in the math library, I'll be updating the travis config here to use Trusty among other things.

quick fix for travis

---

.github/PULL_REQUEST_TEMPLATE.md

fix typo in pull request template

---

.github/PULL_REQUEST_TEMPLATE.md

Updates the pull request template.
Stan Group.

Fixes #2389. Updating pull request template

---

src/docs/stan-reference/functions.tex
src/stan/lang/function_signatures.h
src/test/test-models/good/function-signatures/math/matrix/append_array.stan
src/test/unit/lang/parser/matrix_functions_test.cpp

Replaces https://github.com/stan-dev/stan/pull/2343 (cause I don't have stan-dev access now). It is also rebased on the latest Stan develop branch.
Added append_array function hooks into Stan (stan-dev/math#481) 
./runTests.py src/test/unit/lang/parser/matrix_functions_test.cpp
Added under "Array Concatenation" in src/docs/stan-reference/functions.tex
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): University of California, Santa Barbara

Added signatures, tests, and docs for append_array function (2) (Issue 481)

---

src/stan/lang/compile_functions.hpp
src/stan/lang/compiler.hpp

Fixes documentation imprecision mentioned in issue #2353, as well as a similar one in a different file.
Marco Colombo, University of Edinburgh

Fix docs (#2353).

---

Jenkinsfile
src/stan/callbacks/interrupt.hpp

Jenkinsfile and pipelines

---

src/docs/stan-reference/examples.tex

Fix typo in manual. See issue #2380 
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Charles Margossian

correct x_i typo in Stan

---

src/docs/stan-reference/title.tex

Updates Daniel's affiliation.
None.
Generable

Fixes #2427. Updating Daniel's affiliation

---

make/cpplint

Checks that Python is installed and the version is 2
Provides more helpful message if Python is not installed or if version is 3
PYTHON2=pythonz
make cpplint
PYTHON2=python3
make cpplint
PYTHON2=python2
make cpplint
Gives a warning also when running other make commands
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Aki Vehtari

check that Python exist and that version is 2

---

Jenkinsfile

This is present in the other repos but not here yet.

Add kill old builds step.

---

Jenkinsfile

[Jenkins] Integration tests are always essentially make-only.

---

.github/CONTRIBUTING.md

Add link to introduction to stan for new developers.

---

src/docs/stan-reference/functions.tex
src/docs/stan-reference/language.tex

Fixed a few typos.
Marco Colombo

Fix typos in documentation.

---

src/docs/stan-reference/programs/mining-disasters/changepoint.stan
src/docs/stan-reference/programs/mining-disasters/fit.R

```
Traceback (most recent call last):
File "./runTests.py", line 16, in <module>
"lib", "stan_math", "runTests.py"))
IOError: [Errno 2] No such file or directory
```
```
python: can't open file '/cpplint.py': [Errno 2] No such file or directory
make: *** [cpplint] Error 2
```
- [ x] Declare copyright holder and open-source license: see below
A simple pass tidying up an example.
To reduce confusion among newcomers.
Read.
A larger community.
[Zapier](https://zapier.com) …

Mining disaster example tidy up

---

.travis.yml

[Travis] Fix .travis.yml since we dropped the clang libc++ thing from the makefiles

---

src/docs/stan-reference/appendices.tex

Fixes #2564
Updates the BNF of the Stan modeling languages in the documentation. This only changes documentation.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Jeffrey B. Arnold

Update BNF of Stan language

---

Jenkinsfile

[Jenkins] Use library mailBuildResults, rearrange stages for easier replay

---

Jenkinsfile

[Jenkins] Run upstream CmdStan tests on downstream_tests job.

---

Jenkinsfile

[JenkinsConfig] Always run upstream tests; broke with hotfix

---

Jenkinsfile

I broke Jenkins on develop. This is an attempt to fix that.

[Jenkins] Try accessing shared library directly rather than within a function

---

src/stan/model/indexing/rvalue.hpp

- [] Run unit tests: `./runTests.py src/test/unit`
Since we're already doing our own bounds-checking we can avoid it in `rvalue` (and probably many other places).
Performance improvement

Faster indexing

---

src/stan/lang/rethrow_located.hpp

This refactors rethrow_located to also take in a string to specify the location.
To add more flexibility to rethrow_located to be forward compatible with stanc3.
Look at signature, run unit tests.
-
Wrote docstrings.
Matthijs Vakar, Columbia University

Refactoring rethrow_located to take in a string

---

Jenkinsfile

Changed label of master to oldimac

---

src/stan/model/indexing/lvalue.hpp
src/test/unit/model/indexing/lvalue_test.cpp

We can defer to Eigen's copy constructor now for assignment 

---

src/stan/analyze/mcmc/compute_effective_sample_size.hpp
src/test/unit/analyze/mcmc/compute_effective_sample_size_test.cpp

Fixes #2820 and #2821.
Fix bugs.
Run tests.  Tests were added at edge cases as well to verify appropriate behavior below and above.
None.
Inline.
Michael Betancourt

Fix const logic and size check

---

src/stan/model/grad_hess_log_prob.hpp

1. There was some very weird indexing happening in model/grad_hess_log_prob.hpp where we would grab a reference to a 'row' in the vector representing the hessian. That was weird so I ripped it out and just did normal indexing. This also showed me that we have a very weird memory access pattern when we fill in that vector representing the hessian. I couldn't figure out a nicer access pattern but also don't know how much we use that particular function so I let it go. Also the diagonal is being incremented twice, idk if that's intended or not.
2. `half_epsilon * coefficients[i]` used in the 3rd for loop are both known at the beginning of the function so we move them up
Just a little code cleanup, maybe the next person can figure out a better memory access pattern
Tests should run as normal …

Cleanup grad_hess_log_prob so weird indexing is more obvious

---

README.md

Clarify license implications due to Apache 2.0 Intel TBB.
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Sebastian Weber

add Apache 2.0 license note

---

src/stan/services/diagnose/diagnose.hpp
src/stan/services/experimental/advi/fullrank.hpp
src/stan/services/experimental/advi/meanfield.hpp
src/stan/services/optimize/bfgs.hpp
src/stan/services/optimize/lbfgs.hpp
src/stan/services/optimize/newton.hpp
src/stan/services/sample/fixed_param.hpp
src/stan/services/sample/hmc_nuts_dense_e.hpp
src/stan/services/sample/hmc_nuts_dense_e_adapt.hpp
src/stan/services/sample/hmc_nuts_diag_e.hpp
src/stan/services/sample/hmc_nuts_diag_e_adapt.hpp
src/stan/services/sample/hmc_nuts_unit_e.hpp
src/stan/services/sample/hmc_nuts_unit_e_adapt.hpp
src/stan/services/sample/hmc_static_dense_e.hpp
src/stan/services/sample/hmc_static_dense_e_adapt.hpp
src/stan/services/sample/hmc_static_diag_e.hpp
src/stan/services/sample/hmc_static_diag_e_adapt.hpp
src/stan/services/sample/hmc_static_unit_e.hpp
src/stan/services/sample/hmc_static_unit_e_adapt.hpp
src/stan/services/util/initialize.hpp
src/stan/services/util/read_dense_inv_metric.hpp
src/stan/services/util/read_diag_inv_metric.hpp

Addresses the first part (the easy one) of #2781.
Existing tests should run.
None.
No changes required.
Marco Colombo

Const correctness for io::var_context in stan/services

---

Jenkinsfile

Jenkins will now skip ci/cd pipeline if source code file paths defied in the Jenkinsfile do not have changes.

Skip CI/CD on

---

src/stan/model/indexing/deep_copy.hpp
src/stan/model/indexing/lvalue.hpp
src/stan/model/indexing/rvalue.hpp
src/test/test-models/good/compound-assign/indexed_expr_divide_equals.stan
src/test/unit/model/indexing/lvalue_test.cpp
src/test/unit/model/indexing/rvalue_test.cpp

This reverts commit e6ddc67ac1bcebfdf733105afd93ec4705f70bcc, reversing
changes made to 583b1509dadad60ee1496e07c20edd98adc7ec17.

Revert "Merge pull request #2885 from stan-dev/stan/generic-rvalue"

---

LICENSE.md

#2733 License has been updated to 2020

---

Jenkinsfile

This adds the expressions tests in the Stan repo Jenkins. These tests should be run here because we want these tests to also run on compiler changes (stanc3 will run Stan tests in the near future).
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Rok Češnovar, Univ. of Ljubljana

Run Math expressions tests in Stan Jenkins tests

---

Jenkinsfile
make/tests

This PR adds Windows Integration tests to Jenkins
Rok Češnovar, Univ. of Ljubljana

Add windows integration tests

---

Jenkinsfile

Put clang-format before linting (Issue #2966)

---

Jenkinsfile

Sets O=0 for expression tests
Rok Češnovar, Uni. of Ljubljana

Set O=0 for expression tests

---

src/stan/io/stan_csv_reader.hpp

Fix a spelling error
Keeping Jenkins warmed up

Fixed spelling of adaptation (Cmdstan Issue #971)

---

Jenkinsfile
runTests.py

Fixes GHA tests and adds a way to specify a custom stanc3 binary (required if changes are made in Stan/Math and stanc3 in sync, for example https://github.com/stan-dev/stan/pull/3011).

Fix runtest

---

src/stan/model/model_base_crtp.hpp

Fix for recent clang versions (example reported in https://discourse.mc-stan.org/t/failing-to-make-example-bernoulli-bernoulli-on-cmdstan-fresh-installation/21370).

Remove template from tranform inits call

---

.github/ISSUE_TEMPLATE.md
RELEASE-NOTES.txt
src/doxygen/doxygen.cfg
src/stan/version.hpp
src/test/unit/version_test.cpp

Merge release v2.28.0 into develop

Merge release v2.28.0 into develop

---

.github/ISSUE_TEMPLATE.md
RELEASE-NOTES.txt
src/doxygen/doxygen.cfg
src/stan/callbacks/unique_stream_writer.hpp
src/stan/version.hpp
src/test/unit/version_test.cpp

Essentially what the PR title says.
Rok Češnovar

Merge patch release changes (master to develop)

---

Jenkinsfile
src/stan/mcmc/hmc/hamiltonians/softabs_metric.hpp
src/stan/mcmc/hmc/static_uniform/dense_e_static_uniform.hpp
src/stan/mcmc/hmc/static_uniform/diag_e_static_uniform.hpp
src/stan/mcmc/hmc/static_uniform/softabs_static_uniform.hpp
src/stan/mcmc/hmc/static_uniform/unit_e_static_uniform.hpp
src/stan/services/sample/hmc_nuts_dense_e_adapt.hpp
src/stan/services/sample/hmc_nuts_diag_e_adapt.hpp
src/test/unit/mcmc/hmc/nuts/base_nuts_test.cpp
src/test/unit/mcmc/hmc/nuts_classic/base_nuts_classic_test.cpp
src/test/unit/mcmc/hmc/static/base_static_hmc_test.cpp
src/test/unit/mcmc/hmc/xhmc/base_xhmc_test.cpp
src/test/unit/services/sample/hmc_nuts_dense_e_adapt_parallel_match_test.cpp
src/test/unit/services/sample/hmc_nuts_diag_e_adapt_parallel_match_test.cpp

Replaced git config usage with 'git commit --author'

Replaced git config usage with 'git commit --author'

---

src/stan/model/indexing/rvalue.hpp
src/test/unit/model/indexing/rvalue_test.cpp

Closes https://github.com/stan-dev/cmdstan/issues/1084
Rok Češnovar

Fix matrix indexing

---

Jenkinsfile

See: https://github.com/stan-dev/performance-tests-cmdstan/pull/41

CI to use python3 on the mac instances

---

src/stan/model/indexing/assign_varmat.hpp
src/stan/model/indexing/rvalue.hpp
src/stan/model/indexing/rvalue_varmat.hpp

Cleans up unused variables to remove some compiler warnings.
Rok Češnovar

Remove unused variables

---

.github/ISSUE_TEMPLATE.md
RELEASE-NOTES.txt
src/doxygen/doxygen.cfg
src/stan/version.hpp
src/test/unit/version_test.cpp

Merge the changes in version and release notes to the master branch.

Update version and release notes in master

---

Jenkinsfile

Pass stanc3_bin_url to downstream cmdstan

Improve CI

---

.github/ISSUE_TEMPLATE.md
src/doxygen/doxygen.cfg
src/stan/version.hpp
src/test/unit/version_test.cpp

Prepare version 2.31.0 before Monday's release.

Update versions for release 2.31.0

---

RELEASE-NOTES.txt

This PR will merge the release notes from the release branch into develop.

release/v2.31.0: Release Notes

---

Jenkinsfile

…comment out part of Jenkinsfile for faster debug
WRT https://github.com/stan-dev/ci-scripts/issues/24 we've got a new M1 instance that we need to test our CI on to ensure everything is working fine.
Results should be consistent with the older Mac Instance.

[CI] Ensure mac unit and mac interface are running correctly on m1 instance

---

src/stan/io/deserializer.hpp
src/stan/model/indexing/access_helpers.hpp
src/stan/model/model_base.hpp
src/stan/model/model_base_crtp.hpp
src/stan/services/optimize/laplace_sample.hpp
src/stan/services/sample/standalone_gqs.hpp
src/stan/services/util/generate_transitions.hpp
src/test/unit/model/array_functions_roundtrip_test.cpp

After #3179, the quality gate failed due to warnings. Most of these were doxygen related.
As a note it's probably not good that these warning gates can fail a merge _after_ it passes CI in the PR itself. 

Clean up warnings (primarily doxygen)

---

Jenkinsfile
src/stan/optimization/bfgs.hpp
src/test/unit/services/pathfinder/eight_schools_test.cpp
src/test/unit/services/pathfinder/normal_glm_test.cpp
src/test/unit/services/pathfinder/util.hpp

Fixes a bug for mingw we found via Jenkins. Also changes Jenkins so we always test on windows. @serban-nicusor-toptal somewhat related, is there a way to let jenkins know if a PR is in draft mode or not? That would let us skip the windows tests for draft PRs and then for PRs that are not marked as draft we will run the windows test suite.
Fix mingw bug for ostream
See changes in `test_logger` …

fixes test_logger for mingw

---

src/test/test-models/good-standalone-functions/integrate.stanfuncs

I think this managed to not get picked up earlier because the suffix is not actually .stan

Remove deprecated syntax from test file

---

src/stan/services/pathfinder/multi.hpp
src/stan/services/sample/hmc_nuts_diag_e_adapt.hpp
src/stan/services/sample/hmc_nuts_unit_e_adapt.hpp
src/test/unit/services/sample/hmc_nuts_unit_e_adapt_parallel_test.cpp

Clean up some doxygen and compiler warnings spotted in CI

Clean up various doxygen or compiler warnings

---

src/stan/analyze/mcmc/compute_potential_scale_reduction.hpp

This was leading to some [CI warnings](https://jenkins.flatironinstitute.org/job/Stan/job/Stan/job/develop/234/pipeline_gcc4/folder.-2041684816/)
Resolve warnings

Fix doxygen param names in compute_potential_scale_reduction.hpp
